airbus/discrete-optimization

.github/workflows/build.yml, discrete_optimization/pickup_vrp/solver/lp_solver.py, tests/facility/test_facility_lp.py, tests/facility/test_facility_lp_lns.py, tests/pickup_vrp/builders/linear_flow_solver_runs.py
Some tests were not working if launched with gurobi not installed. 
We fix the issues and add a job launching the test suite without gurobi (for only one entry of matrix os/python-version).
=> Fix issues when gurobi not available

discrete_optimization/coloring/coloring_parser.py, discrete_optimization/facility/facility_parser.py, discrete_optimization/knapsack/knapsack_parser.py, discrete_optimization/rcpsp/rcpsp_parser.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_parser.py, discrete_optimization/tsp/tsp_parser.py, discrete_optimization/vrp/vrp_parser.py
These issues have been automatically detected by codereview.doctor
=> [codereview.doctor] Add encoding when parsing files

discrete_optimization/coloring/solvers/coloring_cp_solvers.py, discrete_optimization/facility/solvers/facility_cp_solvers.py, discrete_optimization/pickup_vrp/solver/ortools_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp_multiskill/solvers/lp_model.py, discrete_optimization/tsp/solver/solver_ortools.py, discrete_optimization/vrp/solver/solver_ortools.py, discrete_optimization/vrp/vrp_toolbox.py, examples/pickup_vrp/loading_example.py, examples/pickup_vrp/plots_wip/animated_plot.py, setup.py
These improvements have been automatically detected by coderview.doctor.
=> [codereview.doctor] Use f-strings

discrete_optimization/generic_tools/lns_cp.py, discrete_optimization/pickup_vrp/solver/lp_solver.py, discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py, discrete_optimization/pickup_vrp/solver/ortools_solver.py, discrete_optimization/rcpsp/solver/calendar_solver_iterative.py, discrete_optimization/rcpsp/solver/cp_lns_methods_preemptive.py, discrete_optimization/rcpsp/solver/rcpsp_cp_lns_solver.py, discrete_optimization/rcpsp_multiskill/fast_function_ms_rcpsp.py, discrete_optimization/rcpsp_multiskill/solvers/calendar_solver_iterative.py, discrete_optimization/vrp/solver/lp_vrp_iterative.py, discrete_optimization/vrp/solver/lp_vrp_iterative_pymip.py
These issues have been automatically detected by codereview.doctor
- Either these trivial conditions are the remaining of development process  => this is fine to remove them
- or they should not be evaluated always to `True `(respectively to `False`) => we should correct them e.g. by removing the `and False` or `or True` that are in the conditions
This PR is removing simply the conditions so that code behaviour is left unchanged but we need a review by someone that actually know what is behind the code (@POPOGO ?)
=> [codereview.doctor] Remove "if" conditions that always evaluate to True or False

discrete_optimization/facility/solvers/gphh_facility.py, discrete_optimization/pickup_vrp/solver/ortools_solver.py, examples/facility/gphh_facility_example.py, examples/knapsack/knapsack_multidimensional.py, examples/knapsack/multiscenario_knap.py, examples/knapsack/solvers_run.py, examples/pickup_vrp/cp_solver_gpdp_example.py, examples/pickup_vrp/linear_flow_solver_examples.py, examples/pickup_vrp/loading_example.py, examples/rcpsp/rcpsp_pareto_example.py, examples/rcpsp/robustness_experiments.py
- Removed the no longer existing lns solver test in gphh_facility_example
- fix a minor bug found in routing ortoolsolver 
- renamed some examples scripts (test->run)
=> Examples Fix and refactoring

discrete_optimization/generic_tools/cp_tools.py, discrete_optimization/rcpsp/fast_function_rcpsp.py, discrete_optimization/rcpsp/minizinc/rcpsp_multi_mode_resource_feasibility_mzn.mzn, discrete_optimization/rcpsp/minizinc/rcpsp_single_mode_resource.mzn, discrete_optimization/rcpsp/rcpsp_utils.py, discrete_optimization/rcpsp/solver/cp_solvers.py, discrete_optimization/rcpsp/solver/rcpsp_pile.py, tests/rcpsp/solver/test_rcpsp_cp.py, tests/rcpsp/solver/test_rcpsp_resource_optim.py
-  new model for resource usage optimisation
-  include a new parameters to params CP (optimisation_level) passed to minizinc solver in the generic minizinc solve function.
=> New model for resource usage optimisation in RCPSP problem

discrete_optimization/coloring/solvers/coloring_toulbar_solver.py, discrete_optimization/coloring/solvers/greedy_coloring.py, examples/coloring/toulbar_coloring_example.py
- modeling of coloring problem as a cfn (see doc here https://toulbar2.github.io/toulbar2/userdoc.html)
- toulbar2 not added as hard dependency because not working on some platform
- example script running fine for platform where pytoulbar2 is provided.
=> Adding new solver for coloring problem based on cost function network

discrete_optimization/datasets.py, discrete_optimization/rcpsp_multiskill/minizinc/mspsp.mzn, discrete_optimization/rcpsp_multiskill/minizinc/mspsp_compatible_all_solvers.mzn, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_mspsp_parser.py, discrete_optimization/rcpsp_multiskill/solvers/cp_solver_mspsp_instlib.py, tests/rcpsp_multiskill/test_mspsp_cp.py
In this PR : 
-we add https://github.com/youngkd/MSPSP-InstLib as a new provider of instance of rcpsp multiskill
-parser .dzn to multiskill discreteoptimisation object.
-new mzn model working on the young's instances with any solver backend
-new unit test testing this new integration.
=> Cleaner integration of model and data  MSPSP-Instlib

discrete_optimization/generic_tools/cp_tools.py
We add the possibility to store status of the solver, such as (sat, unsat, unknown, optimal). Interesting to retrieve for computational experiments.
=> New attribute in CPSolvers : status_solver

discrete_optimization/datasets.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_mslib_parser.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_mspsp_parser.py, examples/rcpsp_multiskill/mslib/mslib_parse_and_solve.py, examples/rcpsp_multiskill/mspsp/mspsp_parse_and_solve.py
New dataset is now integrated in the lib, 
-It is the MSLIB from [Snauwaert, J., & Vanhoucke] available in https://www.projectmanagement.ugent.be/research/project_scheduling/MSRCPSP.
-Fetching function + parsing to discr-opt library and one example of solve is provided.
- Some fixes on the previous dataset included (MSPSP) are also included because it was conflicting with MSLIB dataset.
=> MSLIB (+ polishing MSPSP) integration

discrete_optimization/coloring/coloring_model.py, discrete_optimization/facility/facility_model.py, discrete_optimization/generic_tools/do_mutation.py, discrete_optimization/generic_tools/do_problem.py, discrete_optimization/generic_tools/mutations/mutation_bool.py, discrete_optimization/generic_tools/mutations/mutation_integer.py, discrete_optimization/generic_tools/mutations/permutation_mutations.py, discrete_optimization/knapsack/knapsack_model.py, discrete_optimization/knapsack/knapsack_solvers.py, discrete_optimization/knapsack/mutation/mutation_knapsack.py, discrete_optimization/knapsack/solvers/cp_solvers.py, discrete_optimization/knapsack/solvers/dyn_prog_knapsack.py, discrete_optimization/knapsack/solvers/gphh_knapsack.py, discrete_optimization/knapsack/solvers/greedy_solvers.py, discrete_optimization/knapsack/solvers/knapsack_cpmpy.py, discrete_optimization/knapsack/solvers/knapsack_lns_cp_solver.py, discrete_optimization/knapsack/solvers/knapsack_lns_solver.py, discrete_optimization/knapsack/solvers/lp_solvers.py, discrete_optimization/pickup_vrp/gpdp.py, discrete_optimization/rcpsp/mutations/mutation_rcpsp.py, discrete_optimization/rcpsp/rcpsp_model.py, discrete_optimization/rcpsp/rcpsp_model_preemptive.py, discrete_optimization/rcpsp/specialized_rcpsp/rcpsp_specialized_constraints.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill.py, discrete_optimization/tsp/mutation/mutation_tsp.py, discrete_optimization/tsp/tsp_model.py, discrete_optimization/vrp/mutation/mutation_vrp.py, discrete_optimization/vrp/vrp_model.py, tests/knapsack/test_knapsack_cpmyp.py
We solve issues in knapsack found by 
```
mypy discrete_optimization/knapsack
```
(essentially lack of typing or mistyping, or None not properly handled)
and other issues more generic (impacting other packages) highlighted by mypy errors in knapsack, essentially lack of return types.
=> Fix mypy issues in knapsack

discrete_optimization/generic_tools/cp_tools.py, discrete_optimization/generic_tools/do_mutation.py, discrete_optimization/generic_tools/do_problem.py, discrete_optimization/generic_tools/do_solver.py, discrete_optimization/generic_tools/ea/alternating_ga.py, discrete_optimization/generic_tools/ea/deap_wrappers.py, discrete_optimization/generic_tools/ea/ga.py, discrete_optimization/generic_tools/ea/ga_tools.py, discrete_optimization/generic_tools/ea/nsga.py, discrete_optimization/generic_tools/graph_api.py, discrete_optimization/generic_tools/lns_cp.py, discrete_optimization/generic_tools/lns_mip.py, discrete_optimization/generic_tools/lp_tools.py, discrete_optimization/generic_tools/ls/hill_climber.py, discrete_optimization/generic_tools/ls/local_search.py, discrete_optimization/generic_tools/ls/simulated_annealing.py, discrete_optimization/generic_tools/mip/pymip_tools.py, discrete_optimization/generic_tools/mutations/mixed_mutation.py, discrete_optimization/generic_tools/mutations/mutation_bool.py, discrete_optimization/generic_tools/mutations/mutation_catalog.py, discrete_optimization/generic_tools/mutations/mutation_integer.py, discrete_optimization/generic_tools/mutations/permutation_mutations.py, discrete_optimization/generic_tools/path_tools.py, discrete_optimization/generic_tools/result_storage/multiobj_utils.py, discrete_optimization/generic_tools/result_storage/result_storage.py, discrete_optimization/generic_tools/result_storage/resultcomparator.py, discrete_optimization/generic_tools/robustness/robustness_tool.py
This partially solve new issues arising with stricter mypy shown by
```
mypy discrete_optimization/generic_tools
```
=> Fix generic_tools for stricter mypy

discrete_optimization/coloring/coloring_model.py, discrete_optimization/facility/facility_model.py, discrete_optimization/generic_tools/do_problem.py, discrete_optimization/knapsack/knapsack_model.py, discrete_optimization/rcpsp/rcpsp_model.py, discrete_optimization/rcpsp/rcpsp_model_preemptive.py, discrete_optimization/rcpsp/specialized_rcpsp/rcpsp_specialized_constraints.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill.py, discrete_optimization/tsp/tsp_model.py, discrete_optimization/vrp/vrp_model.py
It simplifies typing and implementing for new developers. ObjectiveRegister.dict_objective_to_doc is now an ObjectiveDoc.
=> Create a dataclass to specify objective type and default weights

discrete_optimization/coloring/solvers/coloring_lp_lns_solvers.py, discrete_optimization/coloring/solvers/coloring_lp_solvers.py, discrete_optimization/facility/solvers/facility_lp_solver.py, discrete_optimization/knapsack/solvers/lp_solvers.py, discrete_optimization/pickup_vrp/solver/lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver_gantt.py, discrete_optimization/tsp/solver/solver_lp_iterative.py, discrete_optimization/vrp/solver/lp_vrp_iterative.py, docs/source/install.md
- this remove some warnings that pops up in pycharm
- this is supposed to be faster
- this has been introduced in gurobi 9
- we add the minimal version for gurobi in install documentation (this is an optional requirement)
=> Replace addConstr() by newer addLConstr() available for gurobi >= 9.0

discrete_optimization/generic_tools/lp_tools.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, examples/rcpsp/rcpsp_lp_cplex_solver.py
- added also a RCPSP CPLEX solver and associated examples
To be able to use it, one needs a have a commercial licence of CPLEX, therefore we don't include it in unit test.
In a long term horizon, we could think about coding "add_var", "add_constr".. function for all the linear programming library. So that for a given problem we would have a unique implementation for the LP model.
=> Add new generic CplexMilpSolver for linear programming using docplex library

credits.md
Thanks @SoulPancake for setting up the file.
=> Adding contributors credits

discrete_optimization/knapsack/knapsack_solvers.py, discrete_optimization/knapsack/solvers/knapsack_asp_solver.py, discrete_optimization/knapsack/solvers/lp_solvers.py, examples/knapsack/knapsack_asp_solver.py, examples/knapsack/solvers_run.py, tests/knapsack/test_knapsack_solvers.py
thanks to @eadietz contribution, new solver for knapsack problem based on Answer set programming modeling.
=> ASP Based solver for knapsack problem

discrete_optimization/knapsack/knapsack_model.py, discrete_optimization/knapsack/solvers/cp_solvers.py, discrete_optimization/knapsack/solvers/greedy_solvers.py, discrete_optimization/knapsack/solvers/knapsack_decomposition.py, examples/knapsack/knapsack_decomposition_solver.py, tests/knapsack/test_knapsack_decomposition_solver.py
We develop a new heuristic solver for knapsack, where random sub-knapsack problem are generated from current solution and solved in order to improve overall solution. It showed good performance using ASP root solver for example.
=> Knapsack iterative solver

discrete_optimization/generic_tools/ea/alternating_ga.py
Was not really alternating between encodings.
=> Fix issue in alternating ga

discrete_optimization/facility/solvers/facility_lp_solver.py, discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py, discrete_optimization/generic_tools/lns_cp.py, discrete_optimization/generic_tools/mutations/mixed_mutation.py, discrete_optimization/pickup_vrp/builders/instance_builders.py, discrete_optimization/rcpsp/fast_function_rcpsp.py, discrete_optimization/rcpsp/rcpsp_model.py, discrete_optimization/rcpsp/rcpsp_model_preemptive.py, discrete_optimization/rcpsp/solver/cp_lns_methods_preemptive.py, discrete_optimization/rcpsp/solver/cpm.py, discrete_optimization/rcpsp/solver/rcpsp_cp_lns_solver.py, discrete_optimization/rcpsp/specialized_rcpsp/rcpsp_specialized_constraints.py, discrete_optimization/rcpsp_multiskill/fast_function_ms_rcpsp.py, discrete_optimization/rcpsp_multiskill/multiskill_to_rcpsp.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill.py, discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_cp_lns_solver.py, discrete_optimization/rcpsp_multiskill/solvers/multimode_transposition.py, discrete_optimization/tsp/common_tools_tsp.py, discrete_optimization/tsp/tsp_model.py, discrete_optimization/vrp/solver/lp_vrp_iterative.py, examples/pickup_vrp/cp_solver_gpdp_example.py
- avoid using deprecated np.int and (-> np.int_) and np.bool (-> np.bool_)
- use np.int_ instead of np.int32 or np.int64. s dtype. This is plateform dependent (correspond to C "long") and is what numpy transforms dtype=int into
- use numba.types.intp instead of numba.types.int32 (same idea as np.int_)
=> Harmonize use of int (32 or 64) and stop using deprecated numpy aliases

discrete_optimization/rcpsp/fast_function_rcpsp.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill.py
- use get_resource_availability_array function in create_fake_tasks_multiskills for a more robust implementation
- de-hard code the minimal duration of subtasts in the numba implementation of SGS for preemptive rcpsp
=> Minor fix for rcpsp and rcpsp_multiskill 

discrete_optimization/generic_tools/ls/simulated_annealing.py, discrete_optimization/pickup_vrp/solver/ortools_solver.py
=> Pass some relevant logger from debug to info

discrete_optimization/generic_rcpsp_tools/gphh_solver.py, discrete_optimization/rcpsp/mutations/mutation_rcpsp.py, discrete_optimization/rcpsp/rcpsp_utils.py, discrete_optimization/rcpsp/solver/cpm.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_pile.py
- gphh was misusing convention of indexing task.
- more robust code when considering mode_details of task in cpm, lp and pile solver
=> Fix Rcpsp modules

discrete_optimization/coloring/coloring_plot.py, discrete_optimization/coloring/solvers/coloring_lp_solvers.py, discrete_optimization/coloring/solvers/greedy_coloring.py
THe index names of nodes of the graph was misused in several solver. (-> hidden misuse when the nodes were integer as it is usually the case)
=> Coloring Fix

discrete_optimization/knapsack/solvers/knapsack_decomposition.py, discrete_optimization/knapsack/solvers/lp_solvers.py, examples/knapsack/knapsack_decomposition_solver.py
- value of knapsack recomputed in LP solver.
- adding an initial_solver option in knapsack_decomposed_solver
=> Fix knapsack

discrete_optimization/rcpsp/rcpsp_utils.py, discrete_optimization/rcpsp/transform_model.py
- managing side effects of PR#127, we still want to be able to construct rcpsp model with special constraint from an existing rcpspmodel without. Thus the function "from_rcpsp_model" is reintroduced in a new module.
- correct potential numpy type issue in a plot function of rcpsp
=> RCPSP development

.github/workflows/build.yml, discrete_optimization/coloring/coloring_model.py, discrete_optimization/coloring/minizinc/coloring_subset_nodes.mzn, discrete_optimization/coloring/solvers/coloring_asp_solver.py, discrete_optimization/coloring/solvers/coloring_cp_lns.py, discrete_optimization/coloring/solvers/coloring_cp_lns_solvers.py, discrete_optimization/coloring/solvers/coloring_cp_solvers.py, discrete_optimization/coloring/solvers/coloring_lp_solvers.py, discrete_optimization/coloring/solvers/coloring_toulbar_solver.py, discrete_optimization/coloring/solvers/greedy_coloring.py, discrete_optimization/generic_tools/graph_api.py, examples/coloring/coloring_asp_solver.py, examples/coloring/toulbar_coloring_example.py, tests/coloring/test_coloring.py
-First change is to allow the possiblity to consider only a subset of nodes in the cost function for coloring
-Problem evaluation functions, and solvers updated accordingly, 
-unit test for the specific feature.
=> Coloring problem enrichment

discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py, discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py, discrete_optimization/generic_rcpsp_tools/solution_repair.py, discrete_optimization/generic_rcpsp_tools/typing.py, discrete_optimization/generic_tools/cp_tools.py, discrete_optimization/generic_tools/graph_api.py, discrete_optimization/rcpsp/rcpsp_model.py, discrete_optimization/rcpsp/rcpsp_solution.py, discrete_optimization/rcpsp/rcpsp_solvers.py, discrete_optimization/rcpsp/rcpsp_utils.py, discrete_optimization/rcpsp/solver/cp_lns_methods_clean.py, discrete_optimization/rcpsp/solver/cp_lns_methods_preemptive.py, discrete_optimization/rcpsp/solver/cp_lns_solver.py, discrete_optimization/rcpsp/solver/cp_solvers.py, discrete_optimization/rcpsp/solver/cpsat_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_pile.py, discrete_optimization/rcpsp/special_constraints.py, examples/rcpsp/rcpsp_cpsat_solver_example.py, tests/rcpsp/solver/test_rcpsp_cp.py, tests/rcpsp/test_rcpsp_preemptive.py
-This is a develop branch when new solver has been implemented for RCPSP and notably some custom model to optimize the resource consumption.
-fix of PileSolver is included as part of the PR as it was not necessarly working with any kind of task ids.
=> New solver development for RCPSP and some fix

discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py, discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py, examples/rcpsp/rcpsp_lns_example.py, notebooks/RCPSP tutorials/RCPSP-6 Large Neighbourhood Search .ipynb, tests/rcpsp/solver/test_large_neighborhood_search_solver.py
We solve the issue #157  
- problem was happening when trying to call the solver in an instance without addditional constraint and the notebook was failing (silently)
- the bug is now fixed and a unit test is added
=> Fix problem of LargeNeighborhoodSearchRCPSP solver 

discrete_optimization/coloring/coloring_solvers.py, discrete_optimization/coloring/solvers/coloring_cpsat_solver.py, examples/coloring/coloring_cpspat_solver_example.py, tests/coloring/test_coloring.py
=> Adding CPSat solver for graph coloring problem

discrete_optimization/generic_tools/ortools_cpsat_tools.py
When setting ParametersCP.nb_process > 1 (i.e.
ortools.sat.python.cp_model.CPSolver.num_workers >1), ortools use multithreading and the handling of errors via pybind11 is not working correctly. We got something like:
"terminate called after throwing an instance of 'pybind11::error_already_set'" and the python aborts.
So instead of raising an error we store it in a dedicated attribute of the do_solver and call callback.StopSearch(), and once outside ortools we
- either log it if it is an early stop due to a user callback returning True
- or re raise it if it is really an exception (for instance a TrialPruned raised by an OptunaPruningSingleFitCallback)
=> Fix ortools-cpsat-based solver when using several workers

examples/pickup_vrp/optuna_full_example.py
- use a defaultdict for kwargs_fixed_by_solver to avoir having to set empty dict for all solvers not needing kwargs
- add logging to see hyperparameters set for the trial before solving (useful when solve is taking long time or even is making crash the script)
=> Update optuna full example

discrete_optimization/coloring/solvers/coloring_lp_solvers.py, discrete_optimization/facility/solvers/facility_lp_solver.py, discrete_optimization/generic_tools/lp_tools.py, discrete_optimization/knapsack/solvers/lp_solvers.py, discrete_optimization/pickup_vrp/solver/lp_solver.py, discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver_gantt.py, discrete_optimization/rcpsp_multiskill/solvers/lp_model.py, tests/knapsack/test_knapsack_lp_lns_solver.py
Now milp solvers need rather to implement `retrieve_ith_solution()` as they already all loop in the same way to get all solutions.
=> Put in common `MilpSolver.retrieve_solutions()`

discrete_optimization/coloring/solvers/coloring_cpsat_solver.py, discrete_optimization/coloring/solvers/coloring_solver_with_starting_solution.py, discrete_optimization/generic_tools/callbacks/optuna.py, discrete_optimization/generic_tools/cp_tools.py, discrete_optimization/generic_tools/ortools_cpsat_tools.py, examples/coloring/coloring_cpspat_solver_example.py, examples/coloring/optuna_full_example_coloring.py
-Added a CPSat based solver for coloring problem
-In examples, added an optuna hyperparameter study on the cpsat hyperparameters
=> Adding CPSat solver for coloring and new optuna example

discrete_optimization/generic_tools/lp_tools.py, tests/coloring/test_coloring.py
Was only retrieving the first solution even when asking for all.
=> Fix retrieve_solutions() for milp solvers

discrete_optimization/generic_tools/callbacks/loggers.py, examples/rcpsp/rcpsp_cpsat_solver_example.py
-new callback that logs current best objective function -example of use in one example script
=> Adding objective function logger callback

discrete_optimization/knapsack/solvers/cp_solvers.py, discrete_optimization/knapsack/solvers/dyn_prog_knapsack.py, discrete_optimization/knapsack/solvers/gphh_knapsack.py, discrete_optimization/knapsack/solvers/knapsack_decomposition.py
Add relevant hyperparams to solver of knapsack. 
This will allow for more advanced optuna experiments.
- few points to note : 
- gphh solver doesn't seem very satisfactory, there was already a comprehensive object to set hyperparameters
- decomposition solver not fully satisfactory since some hyperparams are solver themselves which then opens to more hyperparams proper to each solver
=> Knapsack solver hyperparameters

discrete_optimization/rcpsp/solver/cpsat_solver.py
Trivial : 
This allows to use this solver (and subclass) with the solve() function implemented in rcpsp.rcpsp_solvers
=> Adding kwargs in constructor function of CPSatSolver of Rcpsp

discrete_optimization/knapsack/solvers/knapsack_decomposition.py, examples/knapsack/knapsack_decomposition_solver.py, examples/knapsack/optuna_example.py, tests/knapsack/test_knapsack_decomposition_solver.py
- split hyperparameters for subsolvers in dedicated kwargs:
initial_solver_kwargs and root_solver_kwargs
- add these kwargs and associated subsolvers in hyperparameters
definition
- update tests and examples accordingly
=> Handle subsolvers hyperparameters in knapsack decomposition solver

discrete_optimization/facility/solvers/facility_cp_solvers.py, discrete_optimization/facility/solvers/facility_lp_solver.py
All in the title : added params for LP and CP solvers
=> Adding hyperparams for facility solvers

discrete_optimization/knapsack/solvers/cp_solvers.py, discrete_optimization/knapsack/solvers/dyn_prog_knapsack.py, examples/knapsack/optuna_example.py
- Running optuna_example helped identify minor problem on KnapsackDynProg solver (silent bug), and on retrieve solution of a CP solver
- update the optuna example script to run some more interesting experiment.
=> Update Knapsack solver and optuna examples

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py, tests/generic_tools/hyperparameters/test_hyperparameter.py
Was not taking into account choices arg
Also add kwargs to all suggest_with_optuna signature
=> Fix CategoricalHyperparameter.suggest_with_optuna()

.github/workflows/build.yml, docs/generate_nb_index.py, notebooks/Knapsack tutorial.ipynb, notebooks/RCPSP tutorials/RCPSP-1 Introduction.ipynb, notebooks/RCPSP tutorials/RCPSP-2 Heuristics Solving.ipynb, notebooks/RCPSP tutorials/RCPSP-3 Local search.ipynb, notebooks/RCPSP tutorials/RCPSP-4 Linear programming.ipynb, notebooks/RCPSP tutorials/RCPSP-5 Constraint Programming.ipynb, notebooks/RCPSP tutorials/RCPSP-6 Large Neighbourhood Search .ipynb
- add colab links in notebooks page of the doc
- add a cell in each notebook installing d-o
- update this cell for the release doc
See the generated docs:
- for [default branch](https://nhuet.github.io/discrete-optimization/main/notebooks.html#rcpsp-tutorials)
- for [releases](https://nhuet.github.io/discrete-optimization/0.0.30/notebooks.html#rcpsp-tutorials)
=> Add colab links for notebooks

discrete_optimization/coloring/coloring_solvers.py, discrete_optimization/coloring/solvers/coloring_asp_solver.py, discrete_optimization/coloring/solvers/coloring_cp_solvers.py, discrete_optimization/coloring/solvers/coloring_lp_solvers.py, discrete_optimization/coloring/solvers/coloring_toulbar_solver.py, discrete_optimization/coloring/solvers/greedy_coloring.py, examples/coloring/optuna_all_solvers_coloring.py, examples/coloring/toulbar_coloring_example.py
[WIP]
added hyperparams for greedy and toulbar2 solver.
Todo : handle missing dependency for toulbar2 and continue on other solvers.
=> Update Hyperparams for coloring solver

binder/environment.yml, discrete_optimization/generic_tools/do_problem.py, examples/coloring/optuna_full_example_all_solvers_timed_pruning.py, notebooks/z_Advanced/optuna.ipynb
- Add optuna notebook 
- Add an example script demonstrating all new features related to optuna
=> Add optuna tutorial

.github/workflows/build.yml
Avoid having a job with weird name coming from the startegy.matrix
=> Clean test workflow matrix

discrete_optimization/generic_rcpsp_tools/ls_solver.py, discrete_optimization/generic_tools/cp_tools.py, discrete_optimization/generic_tools/ea/ga.py, discrete_optimization/rcpsp/solver/cp_solvers.py, discrete_optimization/rcpsp/solver/cp_solvers_multiscenario.py, discrete_optimization/rcpsp/solver/cpsat_solver.py, discrete_optimization/rcpsp/solver/rcpsp_ga_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py, discrete_optimization/rcpsp/solver/rcpsp_lp_solver_gantt.py, discrete_optimization/rcpsp/solver/rcpsp_pile.py, examples/rcpsp/rcpsp_lns_example.py, examples/rcpsp/rcpsp_lp_cplex_solver.py
+ minor updates/typo found on the way
=> Add hyperparameters to rcpsp solvers

discrete_optimization/datasets.py, discrete_optimization/generic_tools/graph_api.py, discrete_optimization/generic_tools/qiskit_tools.py, discrete_optimization/maximum_independent_set/mis_model.py, discrete_optimization/maximum_independent_set/mis_parser.py, discrete_optimization/maximum_independent_set/mis_plot.py, discrete_optimization/maximum_independent_set/mis_solvers.py, discrete_optimization/maximum_independent_set/solvers/mis_gurobi.py, discrete_optimization/maximum_independent_set/solvers/mis_kamis.py, discrete_optimization/maximum_independent_set/solvers/mis_ortools.py, discrete_optimization/maximum_independent_set/solvers/mis_quantum.py, discrete_optimization/maximum_independent_set/solvers/mis_solver.py, examples/maximum_independent_set/qiskit_application.py, pyproject.toml, tests/maximum_independent_set/test_maximum_independent_set.py
Add few solvers to solve the maximum independent set problem, like gurobi, ortools, kamis and two solvers using hybrid quantum algorithm with qiskit.
=> Add maximum independent set problem and solvers

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py, discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py, tests/generic_tools/hyperparameters/test_hyperparameter.py
Sometimes, an hyperparameter has meaning only if another one has a specific value (or is in a specific range of values).
Thus we define a new attribute `depends_on`
- if equals to None: no dependency is defined
- else should be (for now) a tuple `(hyperparameter_name, possible_values)`: the considered hyperparameter will be defined (and suggested by optuna) only if the hyperparameter whose name is `hyperparameter_name` have values falling in `possible_values`. `possible_values` must be of `Container` type so that we can test `value in possible_values`. For instance a list, a set or a pandas.Interval.
When suggesting hyperparameters, we suggest them in an order respecting that depencies, by making use of
networkx.alogorithms.dag.topological_sort.
Note that SubBrickKwargsHyperparameter …
=> Allow hyperparameter definition dependending on other hyperparameters

discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py, discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
- add a "high" value for each hyperparameter (can still be tuned in a specific study)
- when their are used as subbrick as only class, use subbrick_cls to avoid having a useless subbrick hyperparameter always set to ParamsConstraintBuilder
=> Update ParamsConstraintBuilder hyperparameters

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py, tests/generic_tools/hyperparameters/test_hyperparameter.py
add a step parameter to the class IntegerHyperparameter
=> add a step parameter to the class IntegerHyperparameter

discrete_optimization/facility/solvers/gphh_facility.py, discrete_optimization/generic_rcpsp_tools/gphh_solver.py, discrete_optimization/knapsack/solvers/gphh_knapsack.py, discrete_optimization/rcpsp/rcpsp_solvers.py, discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_solvers.py
In that case it uses training_domains = [problem].
=> Allow GPHH solvers to not define training_domains

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py, tests/generic_tools/hyperparameters/test_hyperparameter.py
Useful when using copy_and_update_hyperparameters() on such EnumHyperparameter.
=> Add possibility of defining subchoices for EnumHyperparameter

examples/rcpsp/optuna_all_solvers_multiple_instances.py
When gurobi not installed : we discard its use as backend solver by minizinc solvers (CP solver and largeneighborhoodsearch)
We also remote the native LP solvers using gurobi (removing solver that are instances of GurobiMilpSolver)
=> More precise solver and hyperparameters settings to handle missing gurobi solver/licence

discrete_optimization/generic_tools/qiskit_tools.py, discrete_optimization/maximum_independent_set/solvers/mis_quantum.py, pyproject.toml
- if not installed, the relevant modules raise a warning
- will be installed with discrete-optimization[quantum]
=> Make qiskit an optional dependency

discrete_optimization/facility/solvers/facility_lp_solver.py, discrete_optimization/facility/solvers/greedy_solvers.py, discrete_optimization/generic_tools/robustness/robustness_tool.py, discrete_optimization/pickup_vrp/gpdp.py, discrete_optimization/tsp/common_tools_tsp.py, discrete_optimization/tsp/tsp_model.py
cf https://numpy.org/devdocs/numpy_2_0_migration_guide.html
float_ -> float64
=> Prepare compatibility with numpy 2.0

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py, tests/generic_tools/hyperparameters/test_hyperparameter.py
Optuna allows only None, str, int, float, and bool as values for its suggest_categorical() method.
In order to be able to define hyperparameters with other types, we add possibility to define the choices attribute of CategoricalHyperparameter as a mapping label (usually a str) -> actual value.
It would allow any arbitrary value for such hyperparameter. For instance callables for heuristic:
```python
def bee1_impl(x):
return x + 1
def bee2_impl(x):
return x + 2
class SolverWithCallableHyperparameter(SolverDO):
hyperparameters = [
IntegerHyperparameter("nb", low=0, high=2, default=1),
FloatHyperparameter("coeff", low=-1.0, high=1.0, default=1.0),
CategoricalHyperparameter(
"heuristic",
choices={
"bee1": bee1_impl,
"bee2": bee2_impl,
},
default=bee1_impl,
),
EnumHyperparameter("method", …
```
=> Add possibility to specify labels for CategoricalHyperparameter

pyproject.toml
Duplicate dependencies have been merged.
=> Clean pyproject.toml

discrete_optimization/coloring/coloring_model.py, discrete_optimization/coloring/solvers/coloring_quantum.py, discrete_optimization/generic_tools/qiskit_tools.py, discrete_optimization/generic_tools/quantum_solvers.py, discrete_optimization/maximum_independent_set/solvers/mis_quantum.py, discrete_optimization/tsp/solver/tsp_quantum.py, discrete_optimization/tsp/tsp_model.py, examples/qiskit_examples/TSP_example.py, examples/qiskit_examples/coloring_example.py, examples/qiskit_examples/qiskit_optuna_tsp.py, tests/quantum/quantum.py
Add quantum solvers for tsp2Dmodel problem + modify coloring model and tsp model to take in consideration that solution can be incomplete (i.e a node can have no color, a permutation can be incomplete)
=> add quantum solvers for tsp2Dmodel problem

discrete_optimization/maximum_independent_set/mis_model.py, discrete_optimization/maximum_independent_set/solvers/mis_lns.py, tests/maximum_independent_set/test_lns.py
- add `get_dummy_solution()` to `MisProblem` (to be used by a `TrivialInitialSolution`)
- implement a constraint handler (for ortools-cpat)
- add a test for the lns ortools-cpsat solver applied to mis
=> Implement lns solver for maximum independent set problem

discrete_optimization/maximum_independent_set/solvers/mis_kamis.py, discrete_optimization/maximum_independent_set/solvers/mis_lns.py, examples/maximum_independent_set/kamis_example.py, examples/maximum_independent_set/lns_cpsat_mis.py
Putting some example script for easier experiments on MIS solving.
=> Example script for MIS

discrete_optimization/maximum_independent_set/mis_solvers.py, discrete_optimization/maximum_independent_set/solvers/mis_asp.py, discrete_optimization/maximum_independent_set/solvers/mis_decomposition.py, discrete_optimization/maximum_independent_set/solvers/mis_ortools.py, discrete_optimization/maximum_independent_set/solvers/mis_toulbar.py, examples/maximum_independent_set/lns_cpsat_mis.py, examples/maximum_independent_set/mis_decomposition.py, examples/maximum_independent_set/toulbar_mis_example.py, tests/maximum_independent_set/test_lns.py, tests/maximum_independent_set/test_maximum_independent_set.py, tests/maximum_independent_set/test_mis_decomposition.py
- adding a decomposition solver (create a subproblem that can represent a small MIS problem, solve it etc)
- adding a clingo/asp solver, toulbar2 solver
- added example scripts for those solvers
=> New solver added for maximum independent set

discrete_optimization/generic_tools/lexico_tools.py, examples/rcpsp/rcpsp_ortools_lexico.py, tests/rcpsp/solver/test_rcpsp_ortools_lexico.py
- added rcpsp example in the dedicated folder
- change the unit test for rcpsp using callback to save result of each phase of the solver (more robust one !)
- possibility to pass subsolver callbacks in each solving step of the lexico.
=> Lexico tools update

discrete_optimization/tsp/solver/tsp_cpsat_lns.py, discrete_optimization/tsp/solver/tsp_cpsat_solver.py, discrete_optimization/vrp/plots/plot_vrp.py, discrete_optimization/vrp/solver/vrp_cpsat_lns.py, discrete_optimization/vrp/solver/vrp_cpsat_solver.py, examples/vrp/vrp_cpsat_example.py, tests/tsp/test_tsp_cpsat.py, tests/vrp/test_vrp_cpsat.py
-native cpsat model for vrp problem
-added lns constraint handler adapted for vrp
=> CPSat solver for vrp problem

discrete_optimization/coloring/solvers/coloring_cp_lns_solvers.py, tests/coloring/test_coloring_lns_cpsat.py
- added a cpsat constraint handler
- add unit test
=> LNS with cpsat for the coloring graph problem

discrete_optimization/generic_tools/ortools_cpsat_tools.py
This will use some future usage that needs to retrieves easily values of stored variables after a solve call
=> Store CPSolver in the OrtoolsCPSatSolver

discrete_optimization/generic_tools/optuna/utils.py
Pros
- make them different than actual pruned ones
- automatically filtered out in dashboard
Cons
- log in console a bit less readable as traceback is displayed each time
How:
- raise a TrialDropped (custom) error
- catch it in study.optimize to avoid stopping the study
=> Drop trials with same parameters as others by failing them

discrete_optimization/datasets.py
Warning: the files have same names, and even same headers (first lines) but still differences in their content...
=> Update fetching of IMOPSE datasets

discrete_optimization/generic_tools/ls/hill_climber.py, notebooks/RCPSP tutorials/RCPSP-1 Introduction.ipynb, notebooks/RCPSP tutorials/RCPSP-2 Heuristics Solving.ipynb, notebooks/z_Advanced/optuna.ipynb
- fix a bug in `HillPareto`
- fix image link
- mention `generic_optuna_experiment_monoproblem()`
=> Update and fix notebooks

discrete_optimization/rcpsp_multiskill/rcpsp_multiskill_mslib_parser.py, discrete_optimization/rcpsp_multiskill/solvers/cpsat_msrcpsp_solver.py, examples/rcpsp_multiskill/mslib/mslib_parse_and_solve.py, tests/rcpsp_multiskill/test_mspsp_imopse_cpsat.py
First basic native cpsat model for multiskill problem.
- the cpsat model should be quite flexible to different variants of multiskill model :
- variants with 1 worker per task
- possibly only 1 skill used per worker for a given task (which is the most used mcpsp in the litterature but not really the one coded so far in do)
=> CPSat solver for multiskill rcpsp

examples/knapsack/knapsack_mathopt_solver.py
- basically useless PR but example are sometimes easier to run that test.
=> Adding basic example of mathopt for knapsack

examples/rcpsp_multiskill/optuna_expe/optuna_expe.py
-provide one example of use of our optuna utils for the msrcpsp case
=> Optuna example for MSRCPSP

tests/rcpsp_multiskill/test_rcpsp_ms_lp_mathopt.py
- this change of unit test is mostly for actions to pass on mac os python3.12 : the use of LP solver using cbc solver backend is indeed failing recently. 
- Todo : solve the cbc issue
=> Changed the unit test testing

.github/workflows/build.yml, binder/postBuild, notebooks/Knapsack tutorial.ipynb, notebooks/RCPSP tutorials/RCPSP-1 Introduction.ipynb, notebooks/RCPSP tutorials/RCPSP-2 Heuristics Solving.ipynb, notebooks/RCPSP tutorials/RCPSP-3 Local search.ipynb, notebooks/RCPSP tutorials/RCPSP-4 Linear programming.ipynb, notebooks/RCPSP tutorials/RCPSP-5 Constraint Programming.ipynb, notebooks/RCPSP tutorials/RCPSP-6 Large Neighbourhood Search .ipynb, notebooks/z_Advanced/callbacks.ipynb, notebooks/z_Advanced/lexico.ipynb, notebooks/z_Advanced/optuna.ipynb, notebooks/z_Advanced/sequential_metasolver.ipynb
Remove also last mention of DO_SKIP_MZN_CHECK in doc generation.
=> Update minizinc version in notebooks and binder env

discrete_optimization/tsp/solver/tsp_gpdp_solver.py, examples/tsp/run_tsp_gpdp.py, examples/tsp/run_tsp_ls.py, examples/tsp/run_tsp_ortools.py, examples/tsp/run_tsp_sequential.py, tests/tsp/test_tsp_gpdp_based.py
- added possibility to solve tsp by calling the more complicated Gpdp solver,
- added more example of solving tsp problems.
=> TSP updates

discrete_optimization/facility/facility_model.py
=> Fix wrong implementation of the capacity check of the facility problem.

discrete_optimization/fjsp/solvers/__init__.py, discrete_optimization/fjsp/solvers/cpsat_lns_fjsp_solver.py
-adding copyright and __init__ file
-add warmstart in the constraint handler for fjsp
=> Minor changes in fjsp solvers

discrete_optimization/vrp/solver/solver_ortools.py
-fix bug in the basicroutingmonitor
-change verbosity level in the monitor
=> Fix vrp callback in solver ortools

.github/workflows/build.yml
Macos-12 runner is bound to be removed soon:
https://github.com/actions/runner-images/issues/10721
=> Github runner macos-12 replaced by macos-13

discrete_optimization/tsp/solvers/ortools.py
-set time limit (previously hardcoded)
-call init_model when the routing object is none
=> TSP with ortools update

discrete_optimization/coloring/problem.py, discrete_optimization/coloring/solvers/dp.py, discrete_optimization/facility/solvers/dp.py, discrete_optimization/fjsp/solvers/dp.py, discrete_optimization/generic_tools/dyn_prog_tools.py, discrete_optimization/jsp/solvers/dp.py, discrete_optimization/knapsack/solvers/dp.py, discrete_optimization/maximum_independent_set/solvers/dp.py, discrete_optimization/rcpsp/solvers/dp.py, discrete_optimization/tsp/solvers/dp.py, discrete_optimization/vrp/solvers/dp.py, examples/coloring/dp.py, examples/facility/dp.py, examples/fjsp/dp.py, examples/jsp/dp.py, examples/knapsack/dp.py, examples/maximum_independent_set/dp.py, examples/rcpsp/dp.py, examples/tsp/dp.py, examples/tsp/sequential.py, examples/vrp/dp.py, tests/coloring/solvers/test_dp.py, tests/facility/solvers/test_dp.py, tests/fjsp/solvers/test_dp.py, tests/jsp/solvers/test_dp.py, tests/knapsack/solvers/test_dp.py, tests/maximum_independent_set/solvers/test_dp.py, tests/rcpsp/solvers/test_dp.py, tests/tsp/solvers/test_dp.py, tests/vrp/solvers/test_dp.py
-we implement warmstart mixin for Dp solvers
-implement example and test associated
=> Implement warmstart for DP solver/models

discrete_optimization/generic_tools/lns_tools.py, tests/rcpsp/solvers/test_lns.py
- Fix ConstraintHandlerMix for minizinc subsolvers (and add test)
- Raise errors when lns has no initial_solution_provider but does not skip the initial phase or when it does not return a solution
=> Fix lns init phase + constraint handler mix for minizinc subsolvers

.github/workflows/build.yml, discrete_optimization/coloring/solvers/toulbar.py, discrete_optimization/maximum_independent_set/solvers/toulbar.py, examples/coloring/run_toulbar.py, examples/maximum_independent_set/run_toulbar.py, pyproject.toml, tests/coloring/solvers/test_toulbar.py, tests/maximum_independent_set/solvers/test_toulbar.py
-In this PR, we implement the WarmstartMixin for the 2 toulbar2 based solver.
-pytoulbar2 is set as optional dependencies in the project, and is now tested on compatible instances.
=> Toulbar2 closer integration

discrete_optimization/facility/solvers/toulbar.py, discrete_optimization/generic_tools/toulbar_tools.py, discrete_optimization/rcpsp/solvers/toulbar.py
=> Update toulbar  base solver to use callback and minor kwargs passing in some models

discrete_optimization/gpdp/solvers/ortools_routing.py
Starting from 9.12, routing search status becomes a "true" enum (ortools enums).
=> Update way of retrieving ortools routing search status for ortools>=9.12

discrete_optimization/datasets.py, tests/fjsp/solvers/test_cpsat.py, tests/fjsp/solvers/test_dp.py, tests/fjsp/solvers/test_lns.py
Retrieving fjsp on github runners seem very unstable lately. So we skip related tests for now.
=> Temporary skip fjsp tests needing fjsp datasets

discrete_optimization/coloring/solvers/cpmpy.py, discrete_optimization/generic_tools/cpmpy_tools.py, discrete_optimization/generic_tools/unsat_tools.py, discrete_optimization/knapsack/solvers/cpmpy.py, tests/coloring/solvers/test_solvers.py, tests/knapsack/solvers/test_cpmpy.py, tests/knapsack/solvers/test_cpmyp.py
- Derived in knapsack
- Has a dedicated method to explain unsatisfiability
=> Introduce a generic cpmpy solver

examples/coloring/run_unsat_interactive_fine.py, examples/coloring/run_unsat_interactive_meta.py
- run_unsat_interactive_fine.py: the user removes constraints one by one from computed mus until satsifiability
- run_unsat_interactive_meta.py: the user removes meta-constraints one by one
=> Add examples with interactive resolution of unsat for coloring

discrete_optimization/generic_tools/cpmpy_tools.py
- now cpmpy is a subclass of CpSolver
- new conflict computation method (using core)
=> Cpmpy wrapper update 

discrete_optimization/binpack/solvers/dp.py, tests/binpack/solvers/conftest.py, tests/binpack/solvers/test_dp.py, tests/binpack/solvers/test_greedy.py, tests/binpack/solvers/test_lp.py, tests/binpack/solvers/test_toulbar.py
- fix DpBinPackSolver hyperparameters to include the ones from base class DpSolver (ie default `solver` param)
=> Add unit tests for binpack solvers

discrete_optimization/binpack/solvers/greedy.py, discrete_optimization/generic_tools/dashboard/dashboard.py, discrete_optimization/rcpsp/solvers/cpm.py, discrete_optimization/workforce/scheduling/solvers/tempo.py, examples/binpack/run_study.py, examples/workforce/scheduling/run_cpsat.py, examples/workforce/scheduling/run_dashboard.py, examples/workforce/scheduling/run_study_tempo.py, examples/workforce/scheduling/run_study_tempo_multiobj.py, examples/workforce/scheduling/run_tempo.py
- we create a new DoSolver for the workforce scheduling problem, calling by command line the **tempo_scheduler** executable you can fin on the [tempo repo](https://gepgitlab.laas.fr/roc/emmanuel-hebrard/tempo)
- Adding a study with Tempo included. To get timestamp of objective improvement and being able to compare it to other solver, we implement a parser of the logs of Tempo, retrieving the cpu time alors with objective value.
=> Wrapper to the Tempo solver for the workforce scheduling problem
