airbus/discrete-optimization

discrete_optimization/rcpsp/fast_function_rcpsp.py

A @njit decorator was commented on a "fast" function.
Probably a debugging manipulation that have been commited by mistake.

Restore @njit decorator for sgs_fast_preemptive_minduration()

---

README.md

The new README.md did not pass linters. Moreover the verb was in plural form and a point was missing, lefting the sentence unfinished.

Fix typo and finish a sentence.

---

discrete_optimization/rcpsp_multiskill/multiskill_to_rcpsp.py
tests/rcpsp_multiskill/test_rcpsp_ms_to_rcpsp.py

From time to time, the tests in tests/rcpsp_multiskill/test_rcpsp_ms_to_rcpsp.py fail beacause they do not find a solution in time. We try to relax a bit the time conditions on the solver, going partially back on changes from commit df20a0e.

Allow more time for rcpsp_ms to rcpsp solver

---

discrete_optimization/pickup_vrp/solver/lp_solver.py
examples/pickup_vrp/linear_flow_solver_examples.py
tests/pickup_vrp/builders/test_linear_flow_solver.py

We make work tests inside tests/pickup_vrp/builders/linear_flow_solver_runs.py
- We change the input files, in orderto be run with  the free gurobi license
- We change settings for usecase generation , in order to be run with the free gurobi license
- We move a more complex usecase into the examples
- We rename the test file to be discovered by pytest
- We skip a test because `build_pruned_problem()` is buggy for now
- We remove useless prints

Add linear flow solver pickup_vrp test

---

.github/workflows/build.yml
setup.py

Make use of pytest-cov plugin (and coverage library) to export a test coverage report.

Create a coverage report

---

discrete_optimization/knapsack/knapsack_model.py

These improvements have been automatically detected by coderview.doctor.
See https://codereview.doctor/features/python/best-practice/avoid-named-tuple-use-dataclass
for more explanation.

[coderview.doctor] Use dataclass instead of NamedTuple

---

discrete_optimization/facility/solvers/facility_cp_solvers.py
discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py
discrete_optimization/rcpsp/solver/cp_solvers.py
discrete_optimization/rcpsp/solver/rcpsp_pile.py
discrete_optimization/rcpsp_multiskill/solvers/lp_model.py

Some logging messages were bugged because coming from a previous print.
For instance: 
- `print("One solution ", self.objective)` is working while
- `logger.debug("One solution ", self.objective)` is crashing
To see these types of errors during test, one can use `--log-cli-level=DEBUG` option for pytest. We do not that in github workflow because the output is unreadable after that because of other libraries debug messages.
For instance, before this fix 
```
pytest --log-cli-level=DEBUG tests/facility/test_facility_cp.py
```
was crashing. It is now passing.

Fix logging messages

---

README.md

Because of these spaces, the readme subtitles were not rendered correctly.

Replace no break spaces by regular spaces

---

discrete_optimization/rcpsp_multiskill/solvers/lp_model.py

The `init_model()` could crash if employees calendar were shorter than horizon + duration of longer task.
Indeed in [scikit-decide](https://github.com/airbus/scikit-decide), some scheduling tests were crashing because of that. 
This fix ensure that we do not try to access element not in the calendar.

Fix RCSPSP_MS LP solver

---

README.md
discrete_optimization/__init__.py
setup.py

- require version 2.6 for minizinc binary
- check at import of discrete_optimization package that
- minizinc is installed and reachable from PATH
- its version is greater or equal to 2.6.0
- bump minizinc-python to be able to do this check easily from python

Check minizinc binary version and bump minizinc-python version

---

.github/workflows/build.yml

Since PR #48, minizinc is imported in
`discrete_optimization.__init__.py` to check the binary version, so even when fetching tests data.
On windows we need to redefine the `PATH` properly so that minizinc binary is found (while on mac and linux, having it defined at "Add MiniZinc to PATH" step seems sufficient).
The failure happens only if datasets cache retrieval fails itself. See this [job](https://github.com/nhuet/discrete-optimization/actions/runs/3154433525/jobs/5132021850) for instance.

Fix "Fetch data for tests" workflow step for windows

---

discrete_optimization/rcpsp/rcpsp_model.py

-pass additional argument to constructor of RCPSPModel in the copy() function (tasks_list, source_task, sink_task). 
This allows non integer name of task and custom source and sinks as expected.

Fix the copy() function of RCPSPModel

---

.github/workflows/build.yml

Actions running on node 12 will not work anymore in summer 2023 and are
now raising warnings:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
So:
- we update when possible actions version to ones using node 16 instead of 12.
- we stop using deprecated pre-commit/action and replace it by simple call to pre-commit in a shell (mimicking pre-commit/action@v3)
- we replace softprops/action-gh-release by ncipollo/release-action@v1 which is using node 16

Update actions to use node 16

---

index.html

We prepare this branch to be used for github pages:
- tell that it is not a jekyll site
- redirect home page to master/ directory: in PR #56, we make so that all push to default branch build and deploy the doc to a directory in gh-pages with the name of the branch (here master). Release tags will trigger a build and deployment in a directory named after the version number. Having directories at the root of gh-pages with all versions of the documentation will ease the creation of a menu to navigate between versions. By default, the user will arrive on master doc.

Prepare gh-pages for doc deployment

---

.github/workflows/build.yml

The command set-output is now deprecated and we have now to use environment files to define step outputs:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use new way of setting output parameter

---

.github/workflows/build.yml

It simplifies a bit the workflow as we remove 2 steps in general (getting the pip cache path which depends on plateform and then using the cache action itself).
However the action relies on the existence of "requirements.txt" files or at least of a file which manage the required dependencies.
Thus for "linter" and "build" job, we have a small step creating this file (respectively with only pre-commit, or build as defined dependencies).

Use new feature caching pip cache with setup-python action

---

discrete_optimization/knapsack/solvers/knapsack_cpmpy.py
examples/knapsack/knapsack_cpmyp.py
pyproject.toml
tests/knapsack/test_knapsack_cpmyp.py

- Adding a wrapper solver for knapsack using the CP modeling library in python https://github.com/CPMpy/cpmpy
- Adding example to run and unit test
- adding cpmpy as dependency

New knapsack solver based on cpmpy library

---

environment.yml
postBuild
start

Additional files needed to install minzinc properly:
- postBuild: download minizinc AppImage and extract it
- start: set path so that minizinc can be found, run just before jupyter

Create binder environment for discrete-optimization 0.2.0 + python 3.9

---

.github/workflows/build.yml
pyproject.toml
tests/test_import_all_submodules.py

We were missing scipy dependency needed in a lot of modules (espceially rcpsp ones).
Indeed test optional dependencies were installing it. So
- we fix pyproject.toml
- we add a step in workflow which is checking the imports *before* installing the optional dependencies

Fix dependencies of the library and test importing each module correctly

---

discrete_optimization/rcpsp/rcpsp_model.py
tests/rcpsp/test_rcpsp_uncertain_model.py

- the create_rcpsp_model function was not coherent with the new way of handling the source and sink task of the rcpsp problem : 
before, the source was supposed to be the task named "1" et the sink "n_jobs+2", which is no longer the case.

Fix utility function creating sampled rcpsp instance

---

.github/workflows/build.yml

The environment variables needed to generate the proper links were not defined when tagging a release. 
(In that case, $GITHUB_REF starts with "refs/tags")

Fix github+binder links for notebooks when tagging a release

---

notebooks/knapsack.ipynb

The prerequisites are useful only for local users as everything has already been done for binder environment.

Modify prerequisites text for binder users

---

README.md

Avoid duplicate instructions and will ease future maintenance of the installation doc. (Readme will probably not change anymore.)
This is much like what has been done for scikit-decide.

Simplify readme by pointing to online doc

---

docs/source/install.md

Add tips in doc to install minzinc easily in a terminal (works on cloud)

---

postBuild

This fixes potential issues when using gecode.

Add minizinc external lib directory to LD_LIBRARY_PATH in binder environment

---

docs/source/install.md

We add the lib/ directory to `LD_LIBRARY_PATH` to avoid issues with gecode.

Correct minizinc install command lines in doc for Linux without FUSE

---

.github/workflows/build.yml
discrete_optimization/__init__.py
docs/source/install.md

To ensure the library can work, we check in `discrete_optimization.__init__.py` that minizinc binary is installed and configured with the correct version.
But it happens that some users want to use only a part of the library not relying on minizinc. We allow this by skipping the check step if the environment variable `DO_SKIP_MZN_CHECK` is set and evaluates as a boolean to True.
This can be done for instance in shell with
```
export DO_SKIP_MZN_CHECK=1
```

Skip minizinc version check if DO_SKIP_MZN_CHECK env variable is set 

---

docs/README.md

The goal is to avoid having duplicates and be sure to give the most updated piece of information about how to build the docs and how to contribute to the docs.

Make docs/README.md point to contributing page

---

docs/source/conf.py

When extracting the branch name to be used as doc version name, newlines were kept.

[Doc ]Remove newlines at the end of version string coming from git

---

.github/workflows/build.yml

When relaunching a workflow where the action had previously run successfully, the "git commit" will have an non-null exit-code as there is nothing new to commit. So we check that a diff exists before doing a git commit.

Robustify create-binder-env job

---

pyproject.toml

- Require numpy >=1.21 tu use numpy.typing module in particaular NDArray type
- Add typing_extensions as a dependency The goal is to use new typing usage even with older Python version (3.7)

Update dependencies to ease proper typing

---

.pre-commit-config.yaml

Previous version would not install properly with last version of pre-commit.

Bump isort pre-commit hook

---

.github/workflows/build.yml

Even if the build on binderhub servers failed to be launch for some reason (as network issues), it should not mark the whole job creating a new binder env as failed. As the binder environment as already been updated by first steps and the only drawback will be that the first user to click on a binder link will experiment a long waiting time before its notebook actually launches.

Set "trigger binder env build" step as optional in github workflow

---

.github/workflows/build.yml

- Simplify the commands with a for-loop
- Add binderhub servers ovh2 and gke2
- Avoid stopping when one server makes the `trigger_binder.sh` script failing, in order to trigger build on next servers

Improve "trigger binder build" step

---

.github/workflows/build.yml

Tests involving matplotlib plots randomly fail on windows with tkinter backend (e.g. that [workflow](https://github.com/airbus/discrete-optimization/actions/runs/4234233092/attempts/1)) . As suggested [here](https://discourse.matplotlib.org/t/azure-pipeline-is-failing-randomly-when-using-plt-subplots-because-of-tcl/22893/2), we use agg backend instead to avoid that.

Use Agg backend for matplotlib in github actions to avoid random issues in windows tests

---

.github/workflows/build.yml

The federation of binderhubs has changed so we update the urls accordingly.
We also stop triggering a binder build in deploy_release_doc job as it is already done during create-binder-env job.

Update list of binderhubs

---

discrete_optimization/generic_rcpsp_tools/ls_solver.py
discrete_optimization/generic_tools/ea/alternating_ga.py
discrete_optimization/generic_tools/ea/ga.py
discrete_optimization/generic_tools/ea/nsga.py
discrete_optimization/generic_tools/ls/hill_climber.py
discrete_optimization/generic_tools/ls/local_search.py
discrete_optimization/generic_tools/ls/simulated_annealing.py
discrete_optimization/generic_tools/robustness/robustness_tool.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
examples/knapsack/knapsack_multidimensional.py
examples/knapsack/multiscenario_knap.py
examples/pickup_vrp/cp_solver_gpdp_example.py
examples/rcpsp/robustness_experiments.py
tests/knapsack/test_knapsack_ls_solver.py
tests/rcpsp/solver/test_rcpsp_local_search.py
tests/tsp/test_tsp_ls.py

- Remove unused `nb_solutions` attribute from local search solvers
- Remove `current_solution` and `current_objective` from `RestartHandlerLimit.__init__()`: 
objective was already overwritten during local search algo's `solve()` and generally badly initialized in examples (using `model.evaluate()` which gives a dictionary instead of a fitness value).
- Make local search solvers and genetic algorithms derive from SolverDO.

Minor fixes and refactoring on local search and genetic algorithms

---

discrete_optimization/rcpsp/solver/cpsat_solver.py
tests/rcpsp/solver/test_rcpsp_cp.py

- Add a new solver based on ortools-cpsat solver. The model works for multimode-rcpsp, including the variable calendar, non renewable resource.

New solver for RCPSP models

---

.github/workflows/build.yml

The job was not working anymore since the squash enabled with single-commit = true option.
This is due to a bug in `JamesIves/github-pages-deploy-action`: https://github.com/JamesIves/github-pages-deploy-action/issues/1388#issuecomment-1886949424
Thus we commit and push manually versions.json to gh-pages.

Fix update-doc-versions job

---

.github/workflows/build.yml
discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
discrete_optimization/generic_rcpsp_tools/solution_repair.py
discrete_optimization/knapsack/solvers/knapsack_decomposition.py
discrete_optimization/pickup_vrp/solver/lp_solver.py
discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py
discrete_optimization/rcpsp/solver/cp_lns_methods_preemptive.py
discrete_optimization/rcpsp/solver/rcpsp_cp_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_cp_lns_solver.py
discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_lp_lns_solver.py
pyproject.toml

- latest versions of dependencies need python>=3.8
- python 3.7 is not maintained anymore
- we test now for python 3.8 and 3.11

Increase minimal version of python to >=3.8

---

discrete_optimization/generic_tools/result_storage/result_storage.py
discrete_optimization/knapsack/solvers/lp_solvers.py
discrete_optimization/pickup_vrp/gpdp.py
discrete_optimization/pickup_vrp/solver/ortools_solver.py
examples/pickup_vrp/loading_example.py
examples/pickup_vrp/time_windows_example.py
pyproject.toml
tests/pickup_vrp/builders/test_instance_builders.py

- upgrade ortools dependency to >=9.8
- upgrade python minimal version to >=3.8 (ortools 9.8 does not exist for python<3.8 and python 3.7 is not maintained anymore)
- update knapsack solver based on ortools to adapt to the api changes
- update pickup_vrp solver based on ortools
- construct firstsolutionstrategy and localsearchmetaheuristic enum from corresponding ortools pseudo enum
- construct mapping from integer values to ortools solver status from ortools code
- adapt tests and plot functions to work directly with ResultStorage and GPDPSolution instead of specific tuple
- merge solve_intern into solve and construct directly resultstorage on the fly (could be useful to connect logging d-o callbacks or callbacks for hyperparamaters tuning with optuna)
- fix ResultStorage.add_solution …

Update ortools solvers

---

discrete_optimization/vrp/solver/lp_vrp_iterative.py
discrete_optimization/vrp/solver/solver_ortools.py
discrete_optimization/vrp/solver/vrp_solver.py
discrete_optimization/vrp/vrp_toolbox.py
examples/pickup_vrp/loading_example.py
examples/vrp/vrp_solver_example.py
tests/vrp/test_vrp_solver.py

- Some standalone example script for the vrp problem are implemented
- unit test for ortools and greedy vrp solver implemented
- Also took this PR to update the example of the pickup_vrp problems, closely related to classical VRP, so that they run well with latest change in the library.
- fix LP solver for VRP

Adding VRP examples and test + update routing examples

---

.github/workflows/build.yml

Note that upload-artifact and download-artifact v4 have breaking api changes, and deal with new artifacts so they need to be changed together. For instance, artifacts are now immutable. 
See https://github.com/actions/upload-artifact/blob/main/README.md#v4---whats-new for more details.

Update github actions to use node 20 instead of node 16

---

discrete_optimization/generic_rcpsp_tools/ls_solver.py
discrete_optimization/generic_tools/callbacks/__init__.py
discrete_optimization/generic_tools/callbacks/backup.py
discrete_optimization/generic_tools/callbacks/callback.py
discrete_optimization/generic_tools/callbacks/early_stoppers.py
discrete_optimization/generic_tools/callbacks/loggers.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/ls/hill_climber.py
discrete_optimization/generic_tools/ls/simulated_annealing.py
discrete_optimization/generic_tools/robustness/robustness_tool.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
examples/knapsack/knapsack_multidimensional.py
examples/knapsack/multiscenario_knap.py
examples/rcpsp/robustness_experiments.py
tests/generic_tools/callbacks/test_sa_with_callbacks.py
tests/knapsack/test_knapsack_ls_solver.py
tests/rcpsp/solver/test_rcpsp_local_search.py

We create a Callback class to be used by solver.solve() to hook at some stages.
This will enable
- logging to tools like Tensorboard or Optuna
- timing out solvers
- early stopping
- discarding not promising trials during hyperparameters tuning
Callback has a few methods to overwrite in order to execute some code
- `on_solve_start()`: at the beginning of solve
- `on_solve_end()`: at the end of solve
- `on_step_end()`: at the end of each iteration
We are deeply inspired by work from others:
- keras: https://github.com/keras-team/keras/blob/v3.0.2/keras/callbacks/callback.py
- tensorflow: https://github.com/tensorflow/tensorflow/blob/cafa8f3bd9b5740d1d37db799eec3168edc7e97b/tensorflow/python/training/session_run_hook.py#L94
- or-tools: …

Add callbacks in `SolverDO.solve()`

---

discrete_optimization/generic_tools/callbacks/early_stoppers.py
discrete_optimization/generic_tools/exceptions.py
discrete_optimization/pickup_vrp/solver/ortools_solver.py
examples/pickup_vrp/loading_example.py
examples/pickup_vrp/time_windows_example.py
tests/generic_tools/callbacks/test_ortools_with_callbacks.py
tests/pickup_vrp/builders/test_instance_builders.py
tests/pickup_vrp/solvers/test_ortools_solver.py

- We plug the callbacks to ortools solver by making use of `SearchMonitor` object
NB: the `on_step_end()` is plugged here in the `AtSolution()` ortools hook. Which means an iteration for d-o `Callback` corresponds to finding a feasible solution for ortools routing solver.
- We remove `n_solutions` parameters from `init_solve()` as 
- it did not work as intended (should have stopped the solve process after finding `n_solutions` solutions);
- it caused segfault when early stopping with callbacks the solve.
- We implement a `NbIterationStopper` callback which will stops the optimization when a given number of iterations is reached.
NB: when using it with `ORToolsGPDP`, it will correspond to the number solutions found as we hooked in `AtSolution()`. So this will replace the previous …

Add callbacks to pickup_vrp ortools solver

---

discrete_optimization/coloring/solvers/greedy_coloring.py

- Use .value instead of .name in greedy coloring solver

Fix parameter usage in greedy coloring so that the code actually works

---

discrete_optimization/generic_tools/callbacks/early_stoppers.py
discrete_optimization/generic_tools/cp_tools.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
discrete_optimization/knapsack/solvers/knapsack_cpsat_solver.py
discrete_optimization/rcpsp/solver/cpsat_solver.py
examples/knapsack/knapsack_cpsat_solver.py
examples/knapsack/knapsack_decomposition_solver.py
tests/knapsack/test_knapsack_cpsat_solver.py
tests/rcpsp/solver/test_rcpsp_cp.py

- Add a generic abstract class `OrtoolsCPSatSolver` for such solvers. 
- A `solve()` is implemented that used an ortools callback for
- updating a result_storage each time a new solution is found by the cpsat solver.
- calling the user (do) callbacks at each new solution, with the possibility of early stopping if the callback return True.
- A method `retrieve_solution()` needs to be implemented to reconstruct a do solution from the current ortools solution found by the cpsat solver. The value of the internal variables are accessible via `cpsolvercb.Value(VARIABLE_NAME)`.
- Update `CPSatRCPSPSolver` to use it.
- Update `CPSatKnapsackSolver` to use it.

Refactor ortools cp-sat based solvers

---

discrete_optimization/rcpsp/solver/cpsat_solver.py

- when no task is consuming a resource, we don't include constraints storing the consumption of this resource, because it leads to failed model. (addMaxEquality most probably or NonOverlap are not compliant with empty list of variables)

Fix corner case of cpsat encoding

---

discrete_optimization/coloring/solvers/coloring_lp_solvers.py
discrete_optimization/facility/solvers/facility_lp_solver.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/knapsack/solvers/lp_solvers.py
discrete_optimization/pickup_vrp/solver/lp_solver.py
discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py
discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_solver_gantt.py
discrete_optimization/rcpsp_multiskill/solvers/lp_model.py
examples/coloring/coloring_gurobi_solver.py
tests/coloring/test_coloring.py

- replace method to implement (for all milp solvers) `retrieve_ith_solution()` by `retrieve_current_solution()` that take a callable  `get_var_value_for_current_solution()`. Then
- `retrieve_ith_solution` is `retrieve_current_solution` with
`get_var_value_for_ith_solution`
- during a gurobi callback, it will be called with `model.cbGetSolution`
- update milp solvers to reflect that
- create a `GurobiCallback` class that
- populates on the fly a result_storage by using
`retreive_current_solution()`
- calls user-defined d-o callbacks
- terminate solve if user-defined callbacks decide to early stop
- add a test using d-o callbacks with gurobi for coloring solver
- the gurobi pickup-vrp solver still does not use callbacks as it is
overriding `GurobiMilpSolver.solve()` to perform a loop.

Implement callbacks integration for gurobi solvers

---

discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
examples/coloring/optuna_full_example_coloring.py
examples/pickup_vrp/optuna_full_example.py
examples/pickup_vrp/pickup_vrp_ortools_with_optuna_auto.py
examples/pickup_vrp/pickup_vrp_ortools_with_optuna_with_pruning_v4_auto.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

- add documentation
- renaming 
- `suggest_hyperparameters_values_with_optuna` -> `suggest_hyperparameters_with_optuna`
- `suggest_hyperparameter_value_with_optuna` -> `suggest_hyperparameter_with_optuna`
- allow names=None for `suggest_hyperparameters_with_optuna() `=> all possible parameters
- `suggest_hyperparameters_with_optuna()` returns now a dict to be directly used as `**kwargs` in `__init__()`, `init_model()`, and `solve()`.
- new hyperparameter types for meta-solvers:
- `SubSolverHyperparameter`: specifying a `SolverDO` class
- `SubSolverKwargsHyperparameter`: specifying the hyperparameters for a given subsolver as a dictionary to  be used as kwargs. The associated `suggest_with_optuna()` actually call the `suggest_hyperparameters_with_optuna()` from the subsolver
- add a method …

Hyperparameters improvements and refactoring

---

discrete_optimization/coloring/solvers/coloring_cpsat_solver.py
discrete_optimization/coloring/solvers/coloring_solver_with_starting_solution.py
discrete_optimization/knapsack/solvers/cp_solvers.py
discrete_optimization/knapsack/solvers/dyn_prog_knapsack.py
discrete_optimization/knapsack/solvers/knapsack_decomposition.py
discrete_optimization/pickup_vrp/solver/ortools_solver.py

The idea is
- to define once for all default values for hyperparameters when
defining them in solver.hyperparameters
- reuse these default values to complete kwargs in solve/init_model in
one line
Thus
- we add default values in hyperparmeters definitons when missing
-  we call `complete_with_default_hyperparameters` before getting
hyperparameter values from kwargs

Update solvers to make them use `complete_with_default_hyperparameters`

---

discrete_optimization/coloring/solvers/coloring_cp_lns.py
discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py
discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/rcpsp/solver/cp_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_cp_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
discrete_optimization/rcpsp_multiskill/solvers/cp_lns_solver.py
discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_cp_lns_solver.py
examples/knapsack/knapsack_multidimensional.py
examples/rcpsp/rcpsp_lns_example.py
tests/facility/test_facility_lp_lns.py
tests/knapsack/test_knapsack_lns_cp_solver.py
tests/knapsack/test_knapsack_lp_lns_solver.py
tests/rcpsp/solver/test_large_neighborhood_search_solver.py
tests/rcpsp/solver/test_rcpsp_cp_lns.py
tests/rcpsp_multiskill/test_rcpsp_ms_cp.py
tests/rcpsp_multiskill/test_rcpsp_ms_lp_lns.py
tests/rcpsp_multiskill/test_rcpsp_ms_to_rcpsp.py

- solve() is an alias of solve_lns() with same arguments
- remove arg max_time_seconds beacause can be handled by callback TimerStopper

Implement callbacks for lns solvers

---

discrete_optimization/generic_tools/callbacks/optuna.py

Optuna callback was relying on `ResultStorage.best_fit` to get the current best fitness. But this property is correctly filled only if  the result_storage has been filled using `add_solution()`. And lost of solvers actually directly append solutions to the attribute `ResultSorage.list_solution_fits`.
So we rather use `ResultStorage_get_best_solution_fit()` which works always.

Fix optuna callback

---

discrete_optimization/rcpsp/rcpsp_parser.py

Included a function "parse_patterson" to read in RCPSP-instances in Patterson file format.
This file format is (by now) much more wide-spread than the explicit file format of PSPLIB-instances.
The "parse_patterson" method is called, if an RCPSP-instance-file ends with ".rcp".
See also here: https://www.projectmanagement.ugent.be/research/project_scheduling/rcpsp
e.g. datasets RG30 and RG300

Modified parse_file function to include the possibility to read in patterson rcpsp files

---

discrete_optimization/generic_tools/callbacks/optuna.py
discrete_optimization/generic_tools/optuna/timed_percentile_pruner.py
examples/coloring/optuna_all_solvers_coloring.py
examples/coloring/optuna_all_solvers_coloring_with_pruning_based_on_time.py
examples/coloring/optuna_all_solvers_coloring_without_pruning.py
examples/coloring/optuna_full_example_coloring.py
examples/knapsack/optuna_example.py
examples/pickup_vrp/optuna_full_example.py
examples/pickup_vrp/pickup_vrp_ortools_with_optuna_with_pruning.py
examples/pickup_vrp/pickup_vrp_ortools_with_optuna_with_pruning_v4.py
examples/pickup_vrp/pickup_vrp_ortools_with_optuna_with_pruning_v4_auto.py
examples/rcpsp/rcpsp_local_search_with_optuna_with_pruning.py
tests/generic_tools/callbacks/test_sa_with_callbacks.py

- We make optuna callbacks store a user_attribute for elapsed time
- We add optuna callbacks reporting intermediate results with elapsed time instead of iteration number
- We add a pruner working with elapsed time by modifying existing pruner so that an interpolation is done on intermediate values of previous trials
- We adapt coloring example to show how it works

Use time instead of number of iteration to display and/or prune the trials with optuna

---

.github/workflows/build.yml

The github runner "macos-latest" is now an aliasfor macos-14 on arm64.
- There is no gurobipy for python 3.8 +  macos arm64, so we use macos-12 (x86_64) instead when testing on python 3.8.
- We use prerelease 1.16 for mip when on macos-latest to avoid an error with cbc-mip, waiting for mip 1.16 to be officially released (see  https://github.com/coin-or/python-mip/issues/335#issuecomment-1986745529)

Fix github actions with macos-latest

---

discrete_optimization/coloring/solvers/coloring_cp_lns.py
discrete_optimization/coloring/solvers/coloring_cp_lns_solvers.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py
discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/knapsack/solvers/knapsack_decomposition.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

- We create a class for "hyperparametrizable" objects, with all stuff related to hyperparameters management
- `SolverDO` derive from `Hyperparametrizable`
- main bricks for LNS solvers also derive from it:
- `ConstraintHandler`
- `InitialSolution`
- `PostProcessSolution`
- We apply this to `LnsCpColoring`

Make easier hyperparameters definition for LNS solvers

---

discrete_optimization/generic_tools/optuna/timed_percentile_pruner.py
pyproject.toml
tests/generic_tools/callbacks/test_sa_with_callbacks.py
tests/test_import_all_submodules.py

- Fix tests/test_import_all_submodules.py
- was not working with python 3.12
- is now using directly the public api of pkgutil
- Add setuptools in requirements to avoid "No module named 'pkg_resources'" with cpmpy
- Skip tests and module relying on optuna if not installed

Fix some issues in preparation for python 3.12 support

---

.github/workflows/build.yml

ortools 9.10 results in segmentation fault on github runner windows-latest.
Could maybe be solved by updating Microsoft Visual C++ Redistributable https://github.com/google/or-tools/issues/4227

Freeze ortools for windows tests

---

discrete_optimization/coloring/solvers/coloring_cp_lns.py
discrete_optimization/coloring/solvers/coloring_cp_lns_solvers.py
discrete_optimization/coloring/solvers/coloring_lp_lns_solvers.py
discrete_optimization/facility/solvers/facility_lp_lns_solver.py
discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py
discrete_optimization/generic_rcpsp_tools/neighbor_builder.py
discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
discrete_optimization/generic_rcpsp_tools/solution_repair.py
discrete_optimization/generic_tools/cp_tools.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/generic_tools/lns_tools.py
discrete_optimization/knapsack/solvers/cp_solvers.py
discrete_optimization/knapsack/solvers/knapsack_lns_cp_solver.py
discrete_optimization/knapsack/solvers/knapsack_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_lp_lns_solver.py
examples/knapsack/knapsack_multidimensional.py
notebooks/Knapsack tutorial.ipynb
notebooks/RCPSP tutorials/RCPSP-6 Large Neighbourhood Search .ipynb
notebooks/z_Advanced/optuna.ipynb
tests/facility/test_facility_lp_lns.py
tests/knapsack/test_knapsack_lns_cp_solver.py
tests/knapsack/test_knapsack_lp_lns_solver.py
tests/rcpsp/solver/test_rcpsp_lp_lns.py
tests/rcpsp_multiskill/test_rcpsp_ms_lp_lns.py

- `LNS_CP` and `LNS_MILP` derive from `BaseLNS` and have a common `solve()`
- constraint handlers used by `LNS_CP` are now called `MznConstraintHandler` and derive from base `ConstraintHandler` (adding `child_instance` parameter)
- `solve_lns()` is removed (replaced by `solve()`)
- `cp_solver` and `milp_solver` parameters become a common parameter `subsolver` parameter
- remove obsolete `LNS_CPlex`

Unify lns solvers api

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

When only one class is possible, instead of having a dedicated hyperparameter with only 1 choice, we directly specify the class in the SubBrickKwargsHyperparameter.

Allow SubBrickKwargsHyperparameter to directly specify a subbrick class

---

discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

Optuna suggestion could raise error when a subbrick could take 2 different classes that have both an hyperparameter with same name but of a different kind. (For instance one being an `IntegerHyperparameter`, the other being a `CategoricalHyperparameter`).
To avoid this issue, we update the hyperparameter prefix when seen as a parameter of an optuna trial to include the actual class name of the chosen subbrick.
For example,
```python
class MySolver(SolverDO):
hyperparameters = [
SubBrickHyperparameter("subsolver", choices=[LPSolver, CPSolver]),
SubBrickKwargsHyperparameter(
"kwargs_subsolver", subbrick_hyperparameter="subsolver"
),
]
...
class LPSolver(SolverDO):
hyperparameters = [
CategoricalHyperparameter("hp", choices=[True, False]),
]
...
class CPSolver(SolverDO):
hyperparameters = [ …
```

Fix issue with subsolvers whose hyperparameters share names but not types

---

discrete_optimization/coloring/solvers/coloring_cpsat_solver.py
discrete_optimization/coloring/solvers/coloring_solver_with_starting_solution.py
discrete_optimization/coloring/solvers/coloring_toulbar_solver.py
discrete_optimization/facility/solvers/facility_lp_solver.py
discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py
discrete_optimization/generic_rcpsp_tools/ls_solver.py
discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
discrete_optimization/generic_tools/lns_tools.py

We specify the dependencies between some hyperparameters to avoid having optuna suggest algorithmically identical trials, whenever the simple `depends_on` current syntax (a single parent hyperparameter with a set of possible values) is sufficient.

Make use of `depends_on` to improve existing solvers hyperparameters definition

---

discrete_optimization/generic_rcpsp_tools/large_neighborhood_search_scheduling.py
discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
discrete_optimization/generic_tools/optuna/timed_percentile_pruner.py
discrete_optimization/generic_tools/optuna/utils.py
discrete_optimization/generic_tools/result_storage/result_storage.py
examples/coloring/optuna_full_example_all_solvers_timed_pruning.py
examples/rcpsp/optuna_all_solvers_multiple_instances.py
tests/generic_tools/optuna/test_optuna_utils.py
tests/generic_tools/test_resultstorage.py

We provide generic functions to help create and run optuna studies
- on a single problem, with ` generic_optuna_experiment_monoproblem()`: this takes into account the latest examples added to examples/, and allow the possibility to report/prune according to elapsed time (meaningful when dealing with several unrelated solvers) or internal optimization step number
- on several problems, with `generic_optuna_experiment_multiproblem()`: as the [example](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.WilcoxonPruner.html#optuna.pruners.WilcoxonPruner) provided in optuna doc for WilcoxonPruner, we report intermediate values and potentially prune after each instance resolution
These generic functions set default values for study name, journal log, ... and one should …

Add Optuna utilities to generate and run studies on single problem instance and multiple problem instances 

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
discrete_optimization/rcpsp/rcpsp_model.py
discrete_optimization/rcpsp/solver/rcpsp_ga_solver.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

a "glitch" was found by running GA_RCPSP solver with a crossover operator that was changing the permutation vector to a non permutation vector. Evaluation function of rcpsp was still functionning because the final task was still scheduled for some hard-to-guess reason. In this PR we try to remove those potentials problems by : 
- insure all task are scheduled in the satisfy function of RCPSP
- reduce the set of hyperparameter value for the crossover operator (but in practice a user can still run the solver with a wrong setting)

More robust satisfy function for rcpsp

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

Will be used as default arg for `trial.suggest_integer()` and `trial.suggest_float()`.
Note: `step` already existed for integer hyperparameter only.

Add log and step attributes to integer and float hyperparameter

---

discrete_optimization/pickup_vrp/gpdp.py

When the problem specifies specific vehicle compatibility (node_vehicle specified in the problem) then we fix the implementation of the get_edges_for_vehicle() function, so the underlying constraint is now well taken into account by Milp based solver for example

Correct initialisation of get_edges_for_vehicle() in GPDP problem

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

If `None`, nothing changes.
Else the `name_in_kwargs` is used as the key for the hyperparameter in the dictionary generated by `solver.suggest_hyperparameters_with_optuna()`.
This is useful when several hyperparameters are defined with different characteristics, are depending on others so that only one is suggested at a time among them, and are all expected to have the same name in `solver.__init__`. For instance if they are the parameters of a submethod which is not controlled by the library and happen to share names.

Add "name_in_kwargs" attribute to hyperparameters

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
tests/generic_tools/hyperparameters/test_hyperparameter.py

Thanks to the new attributes (and corresponding `suggest_with_optuna()` arguments) `suggest_low` and `suggest_high`, we enforce the possibility of suggesting lower or upper bound.
Indeed, by default, optuna will suggest inside the range (low, high) but never reach exactly a bound (except if a step was provided).
To achieve this, a derived categorical hyperparameter is suggested under the hood to decide whether suggesting the lower bound, upper bound, or a float in between. The "generated" hyperparameter will be named as the original hyperparameter, suffixed with ".suggest_bound" and will take as values
- "low": lower bound suggested
- "high": upper bound suggested
- "": usual behaviour

Add possibility to suggest bounds of a float hyperparameter

---

discrete_optimization/generic_tools/optuna/utils.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
examples/coloring/optuna_ortools_cpsat_finetuning.py
tests/coloring/test_coloring.py

We update `ortools.sat.python.cp_model.CPSolver.parameters` according to the new argument `ortools_cpsat_solver_kwargs`.
We use it in a new coloring example to finetune ortools-cpsat with optuna.

Add possibility to finetune ortools-cpsat solvers

---

discrete_optimization/coloring/solvers/coloring_cp_lns_solvers.py
discrete_optimization/coloring/solvers/coloring_lp_lns_solvers.py
discrete_optimization/coloring/solvers/coloring_lp_solvers.py
discrete_optimization/facility/solvers/facility_lp_lns_solver.py
discrete_optimization/facility/solvers/facility_lp_solver.py
discrete_optimization/generic_rcpsp_tools/neighbor_tools_rcpsp.py
discrete_optimization/generic_rcpsp_tools/solution_repair.py
discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/generic_tools/lns_tools.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/knapsack/solvers/cp_solvers.py
discrete_optimization/knapsack/solvers/knapsack_lns_cp_solver.py
discrete_optimization/knapsack/solvers/knapsack_lns_solver.py
discrete_optimization/knapsack/solvers/lp_solvers.py
discrete_optimization/pickup_vrp/solver/lp_solver_pymip.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_solver_gantt.py
discrete_optimization/rcpsp_multiskill/solvers/lp_model.py
discrete_optimization/rcpsp_multiskill/solvers/ms_rcpsp_lp_lns_solver.py

Do not forget to remove new constraints at the end of each lns iteration.
For minizinc lns, it is not doing anything are this is manage by the child instance creation but for mip lns, this is relevant.
We implement `remove_constraints_from_previous_iteration()` once for all in base classes for
- minizinc based constraint handlers (by doing nothing).
- gurobi based constraint handlers
- pymip based constraint handlers
We also unify their api so that the return value for `adding_constraint_from_results_store()`
(and type of previous_constraints in `remove_constraints_from_previous_iteration`)
is always an iterable of constraints. (no more dictionaries)
Add a common `__init__` for `PymipMilpSolver` to ensure that each pymip solvers have
a `milp_solver_name` attribute needed by the constraint …

Fix lns solve() and unify contraint handlers api

---

discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/generic_tools/lns_tools.py
examples/rcpsp/rcpsp_lns_example.py
tests/knapsack/test_knapsack_lns_cp_solver.py
tests/rcpsp/solver/test_large_neighborhood_search_solver.py
tests/rcpsp/solver/test_rcpsp_lp_lns.py
tests/rcpsp_multiskill/test_rcpsp_ms_lp_lns.py

Instead of passing iteration (which was wrongly always pass as 0) to `solve_with_subsolver()`, we pass a boolean `no_previous_solution` which will be true only if we skipped the initial_solution_provider and we are at the first lns iteration. In that case we will use `time_limit_iter0` instead of `time_limit` to start from a "good" solution.
We also
- rename `skip_first_iteration` into `skip_initial_solution_provider`
- skip the initial solution provider also if `self._initial_solution_provider` is `None`
NB: we keep the boolean for optuna hyperparameters suggestion

Fix use of `time_limit_iter0` in LNS_CP

---

discrete_optimization/generic_tools/lns_cp.py
discrete_optimization/knapsack/solvers/knapsack_lns_cp_solver.py
tests/knapsack/test_knapsack_lns_cp_solver.py

- Make a BaseLNS_CP from which will derive LNS_MinizincCP and
LNS_OrtoolsCPSat
- Keep LNS_CP as an alias of LNS_MinzincCP for backward compatibility
- Add a OrtoolsCPSatConstraintHandler base class that handles the
removing of previous constraints on the underlying CpModel
- Implement an ortools-cpsat version of knapsack constraing handler
- Test lns with ortools-cpsat on knapsack

Implement an ortools-cpsat based lns solver

---

discrete_optimization/generic_tools/do_problem.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/lexico_tools.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
discrete_optimization/knapsack/solvers/knapsack_cpsat_solver.py
discrete_optimization/rcpsp/solver/cpsat_solver.py
tests/knapsack/test_knapsack_lexico_ortools_solver.py
tests/rcpsp/solver/test_rcpsp_cp.py
tests/rcpsp/solver/test_rcpsp_ortools_lexico.py

- Add a `LexicoSolver` which makes a given subsolver solve sequentially
several specified objectives, while adding a constraint at each step
to avoid worsening results according to previous objectives
- Add a bunch of methods to implement (with partial default
implementation) so that a solver can be used as a subsolver by
`LexicoSolver`:
- `implements_lexico_api()`: returns `True` if the solver is lexico ready
(ie implement subsequent methods). `LexicoSolver` raise a warning if
this is not the case
- `get_model_objectives_available()`: list of labels available
corresponding to the intern objectives the solver can optimize.
Defaults to keys of the problem's `ObjectiveRegister` (via new method
`problem.get_objective_names()`)
- `set_model_objective()`: update the intern objective the …

Implement lexicographic optimization

---

discrete_optimization/generic_tools/optuna/utils.py
tests/generic_tools/optuna/test_optuna_utils.py

- Manage better callbacks if already in kwargs_fixed_by_solver
- Allow partially defined dict for kwargs_fixed_by_solver and suggest_optuna_kwargs_by_name_by_solver
- Overwrite studies in tests

Improve optuna utils

---

discrete_optimization/vrp/solver/vrp_cpsat_solver.py
examples/vrp/vrp_cpsat_example.py
tests/vrp/test_vrp_cpsat.py

1 constraint was incorrect and was not insuring that when a given vehicle was used it was starting from the starting node.
It had the effect to give produce (sometimes) empty path in the retrieve solution. This should be fixed now.
- better unit test to check if the issue remains.

Fix bug in cpsat vrp model

---

discrete_optimization/coloring/solvers/coloring_quantum.py
discrete_optimization/facility/solvers/gphh_facility.py
discrete_optimization/facility/solvers/greedy_solvers.py
discrete_optimization/generic_rcpsp_tools/gphh_solver.py
discrete_optimization/generic_tools/ea/alternating_ga.py
discrete_optimization/generic_tools/ea/ga.py
discrete_optimization/generic_tools/ls/hill_climber.py
discrete_optimization/generic_tools/ls/simulated_annealing.py
discrete_optimization/generic_tools/qiskit_tools.py
discrete_optimization/generic_tools/sequential_metasolver.py
discrete_optimization/maximum_independent_set/solvers/mis_quantum.py
discrete_optimization/rcpsp/solver/cpm.py
discrete_optimization/rcpsp_multiskill/solvers/multimode_transposition.py
discrete_optimization/tsp/solver/tsp_cp_solver.py
discrete_optimization/tsp/solver/tsp_quantum.py
tests/rcpsp/test_sequential_metasolver.py

- Chain several subsolvers
- Next subsolver warm started by the best solution of the previous one
- subsolvers must inherit from `WarmstartMixin`, except for first one
- `**kwargs` needed in all solvers `__init__()` method as we apply
- `subsolver.__init__(problem=problem, **kwargs)`
- `subsolver.init_model(**kwargs)`
- `subsolver.solve(**kwargs)`

Implement a sequential metasolver

---

discrete_optimization/generic_tools/hyperparameters/hyperparameter.py
discrete_optimization/generic_tools/hyperparameters/hyperparametrizable.py
tests/generic_tools/hyperparameters/test_hyperparameter.py
tests/generic_tools/optuna/test_optuna_utils.py

- Include in returned kwargs the elements in `fixed_hyperparameters` argument (for `Hyperparametrizable`, and thus for `SubBrickKwargsHyperparmeter` and `SubBrickHyperparmeter`);
- Allow to specify by subbrick class the arguments `names`, `kwargs_by_name`, and `fixed_hyperparameters`, thanks to additional arguments `names_by_subbrick`, `kwargs_by_name_by_subbrick`, and `fixed_hyperparameters_by_subbrick`.
See examples of use in new implemented tests.

Improve `SubBrickHyperparmeter.suggest_hyperparameter_with_optuna()`

---

tests/vrp/test_vrp_cpsat.py

when optional_nodes activated, not sure the tsp rebuilt construction is correct, so we skip part of the unit test. 
should fix the random crash in gh machines.

Unit test change for vrp cpsat

---

discrete_optimization/generic_tools/callbacks/optuna.py
tests/generic_tools/callbacks/test_timed_callbacks_n_pruner.py

Starting from optuna 4.0, report steps are automatically converted to integers (as they are meant to be) so that our "trick" of passing the time instead may result in intermediate value being overriden if steps are within the same second.
We thus introduce a unit factor (if 1., nothing change, if 0.001 it converts time to milliseconds) to be able to have a finer granularity.
This is useful to make the corresponding unit test still work without slowing it.

Add a unit factor when reporting time with optuna callback 

---

.github/workflows/build.yml

With the release of ortools 9.11, the windows wf is working again.

Stop limiting ortools for windows tests

---

tests/rcpsp/solver/test_rcpsp_cp.py

We
- shorten the timer of the callback
- lengthen the time_limit of the ortools solver itself
to avoid assert errors which happens if no solution found
- after the callback timer but
- before the solver own timer.

Update test with callback

---

discrete_optimization/generic_tools/qiskit_tools.py
pyproject.toml

The args backend/session for EstimatorV2 have been deprecated in 0.24 (released on 2024/06/11) then removed in 0.30 (released 2024/09/23), in favor of mode (which will be equal to backend or session depending on the situation.

Stop using deprecated/removed arguments from qiskit-ibm-runtime

---

discrete_optimization/rcpsp_multiskill/rcpsp_multiskill.py
discrete_optimization/rcpsp_multiskill/solvers/cpsat_msrcpsp_solver.py

- in this PR we insure in a more robust way that the shape of vector we add together are coherent.
- this solved normally the failed actions appearing on PR #296

Bugs in rcpsp multiskill calendars utils and cpsat solver

---

discrete_optimization/datasets.py
discrete_optimization/jsp/__init__.py
discrete_optimization/jsp/job_shop_parser.py
discrete_optimization/jsp/job_shop_problem.py
discrete_optimization/jsp/job_shop_utils.py
discrete_optimization/jsp/solvers/cpsat_jsp_solver.py
examples/jsp/jsp_cpsat_example.py
examples/jsp/jsp_via_rcpsp.py
tests/jsp/solvers/test_cpsat_jsp.py
tests/jsp/solvers/test_solve_via_rcpsp.py
tests/jsp/test_jsp_parser.py

-adding new problem implementation, that should evolve with more solver integration in the future.
-JSP problem is very famous and classic scheduling problem involving scheduling set of jobs on disjunctive machines.
-adding cpsat model
-adding transformation to rcpsp in utils.

Job shop problem integration

---

.github/workflows/build.yml
discrete_optimization/__init__.py
discrete_optimization/generic_tools/cp_tools.py
discrete_optimization/maximum_independent_set/mis_parser.py
docs/source/install.md
examples/coloring/coloring_asp_solver.py
examples/coloring/coloring_cpspat_solver_example.py
examples/coloring/toulbar_coloring_example.py
examples/knapsack/knapsack_asp_solver.py
examples/knapsack/knapsack_decomposition_solver.py
examples/maximum_independent_set/optuna_example.py
examples/qiskit_examples/qiskit_optuna_coloring.py
examples/qiskit_examples/qiskit_optuna_knapsack.py
examples/qiskit_examples/qiskit_optuna_mis.py
examples/qiskit_examples/qiskit_optuna_tsp.py
examples/rcpsp/rcpsp_lp_cplex_solver.py

Instead, we raise the same error (with explicit message) only when initializing a minizinc-based solver, thanks to the method `find_right_minizinc_solver_name()` used by each solver.
We transform the relevant test in github workflow accordingly, and update the docs.
We also upgrade the minimal requirement to 2.8.

Stop checking minzinc binary at discrete_optimization import

---

discrete_optimization/generic_tools/cp_tools.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
discrete_optimization/rcpsp/solver/cpsat_solver.py
examples/coloring/coloring_cpspat_solver_example.py
examples/jsp/jsp_cpsat_example.py
examples/knapsack/knapsack_cpsat_solver.py
examples/maximum_independent_set/lns_cpsat_mis.py
examples/rcpsp_multiskill/mslib/mslib_parse_and_solve.py
examples/vrp/vrp_cpsat_example.py
tests/coloring/test_coloring_lns_cpsat.py

Gurobi and mathopt give information about solver status. As for minizinc and cpsat, we make it available on the wrapper level.
As we use the same enumeration `StatusSolver`, we move it to `solver_do` module. And thus add for all solvers a `status_solver` attribute, by default equal to unknown and which is used by `is_optimal()` method.
We remove `get_status_solver()` method which was only returning `self.status_solver`.

Add status to lp solvers (and default one to all solvers)

---

discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/lexico_tools.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
discrete_optimization/knapsack/solvers/knapsack_cpsat_solver.py
discrete_optimization/rcpsp/solver/cpsat_solver.py
discrete_optimization/rcpsp_multiskill/solvers/cpsat_msrcpsp_solver.py
examples/rcpsp/rcpsp_ortools_lexico.py
notebooks/z_Advanced/lexico.ipynb
tests/rcpsp/solver/test_rcpsp_ortools_lexico.py

- we want to make it clear that it deals with lexico optimization (e.g. `add_model_constraint` was not very clear)
- we want to avoid confusion with utility methods to be added to share most `init_model()` code for lp or cp solvers (in particular `set_model_objective` and `add_model_constraint`)
- we also replace "intern" by "internal" as a more appropriate english word. This was in particular used in docstring of lexico methods.

Update lexico api

---

discrete_optimization/coloring/solvers/coloring_lp_solvers.py
discrete_optimization/facility/solvers/facility_lp_solver.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/knapsack/solvers/lp_solvers.py
discrete_optimization/maximum_independent_set/solvers/mis_gurobi.py
discrete_optimization/maximum_independent_set/solvers/mis_lp.py
discrete_optimization/maximum_independent_set/solvers/mis_mathopt.py
discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py
discrete_optimization/rcpsp_multiskill/solvers/lp_model.py
tests/coloring/test_coloring.py
tests/facility/test_facility_lp.py

Share as much as possible init_model() between gurobi and mathopt solvers, by using new methods helping creating model, variables and constraints for each framework.
We also added tests for init_model options that were not tested (like `use_cliques` and `greedy_start`).

Unify lp solvers `init_model()` methods 

---

discrete_optimization/rcpsp/solver/rcpsp_lp_solver.py
tests/rcpsp/solver/test_rcpsp_lp.py

We can avoid to call `init_model()` in `set_warm_start()` doing so.
For now we still keep the same behaviour of init_model though, by calling `set_warm_start` at the end of `init_model` to initialize the lp solver (mathopt or gurobi).

Extract `set_warm_start` stuff from init_model in rcpsp milp solvers

---

discrete_optimization/coloring/solvers/coloring_lp_lns_solvers.py
discrete_optimization/facility/solvers/facility_lp_lns_solver.py
discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/knapsack/solvers/knapsack_lns_solver.py
discrete_optimization/rcpsp/solver/rcpsp_lp_lns_solver.py
tests/coloring/test_coloring_lns_lp.py
tests/facility/test_facility_lp_lns.py
tests/knapsack/test_knapsack_lp_lns_solver.py
tests/rcpsp/solver/test_rcpsp_lp_lns.py

- add a base class `OrtoolsMathOptConstraintHandler` managing constraints removal
- add mathopt constraint handlers for each gurobi ones, sharing most of  the code

Add constraint handlers for mathopt solvers 

---

discrete_optimization/generic_tools/lns_mip.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/maximum_independent_set/solvers/mis_mathopt.py
discrete_optimization/pickup_vrp/solver/lp_solver.py
tests/pickup_vrp/builders/test_linear_flow_solver.py

- We put as much code in common as possible
- between gurobi and mathopt version
- between normal/lazy/cluster versions
- We catch on the fly solutions as TemporaryResult during solve_one_iteration() thanks to a dedicated callback
- We put much part of solve() for base classes GurobiMilpSolver and OrtoolsMathOptMilpSolver into optimize_model() in order to make a good use of it (in particular callback stuff) in solve_one_iteration()
- We add some methods to base classes GurobiMilpSolver and OrtoolsMathOptMilpSolver:
- set_random_seed()
- add_linear_constraint_with_indicator() which mimics gurobipy.Model.addGenConstrIndicator()
- We add access to objective during MathOptCallback (by evaluating registered objective): Be careful, by default we use `as_linear_expression`. One has to override …

Adapt pickup-vrp lp iterative solver with ortools/mathopt

---

discrete_optimization/generic_tools/lns_tools.py
tests/coloring/solvers/test_lns_cpsat.py

before:
- kwargs was checked at each iteration
- kwargs["time_limit"] was updated with `time_limit_subsolver` (or `time_limit_subsolver_iter0`) at first iteration so the warning was raised for further iterations
after:
- we check time_limit in kwargs before the loop, only once
- we copy it in kwargs_subsolver to avoid modifying the original dict

Avoid warning at each iteration of lns about subsolver time_limit

---

tests/rcpsp/solvers/test_cp_mzn.py

The solvers sometimes found solutions before TimerStopper timer but not after before the ortools internal timer. (See
https://github.com/g-poveda/discrete-optimization/actions/runs/11292819184/job/31410496255)
So we use instead the NbIterationStopper which will stops as soon as a solution is found before the ortools internal timer.

Update test with callback for rcpsp/cp_mzn that randomly failed

---

discrete_optimization/generic_tools/dyn_prog_tools.py

The introspection capabilities of python3.9 doesn't cover our needs so we include a try except case and do a temporary fix of kwargs parameters (not as robust as introspection) but that should allow 3.9 user to use DP solvers still

Handle failed introspection on the dp solvers

---

discrete_optimization/generic_tools/dyn_prog_tools.py
examples/coloring/run_dp.py
examples/facility/run_dp.py
examples/fjsp/run_dp.py
examples/jsp/run_dp.py
examples/knapsack/run_dp.py
examples/maximum_independent_set/run_dp.py
examples/rcpsp/run_dp.py
examples/tsp/run_dp.py
examples/vrp/run_dp.py
tests/coloring/solvers/test_dp.py
tests/facility/solvers/test_dp.py
tests/fjsp/solvers/test_dp.py
tests/jsp/solvers/test_dp.py
tests/knapsack/solvers/test_dp.py
tests/maximum_independent_set/solvers/test_dp.py
tests/rcpsp/solvers/test_dp.py
tests/tsp/solvers/test_dp.py
tests/vrp/solvers/test_dp.py

- rename it into retrieve_intermediate_solutions (more explicit)
- set it by default to True (in order to mirror what is done by other solvers)
Note: if retrieve_intermediate_solutions is False, the user callbacks will be called only once, for the last (and only) solution found.

Rename and change default value of use_callback in DpSolver.solve()

---

notebooks/RCPSP tutorials/RCPSP-6 Large Neighbourhood Search .ipynb

- the constraint-handler specific to rcpsp does not exist anymore
- => we skip the part using the base lns solver
- we adapt the arguments used by LnsCpMznGenericRcpspSolver
- remove or rename not relevant parameters

Update rcpsp + lns tutorial

---

discrete_optimization/generic_tools/ortools_cpsat_tools.py
tests/fjsp/solvers/test_cpsat.py

we store the callback in the attrbute of the solver.
This can ease the usage of classical DO callback to retrieve advanced statistic of the solver, such as current bound of the cpsat solver. (example to come)

Adding cpsat callback in the solver attributes

---

discrete_optimization/fjsp/solvers/dp.py
discrete_optimization/generic_tools/qiskit_tools.py
discrete_optimization/jsp/solvers/dp.py
discrete_optimization/rcpsp/utils.py
discrete_optimization/vrp/solvers/lp_iterative.py

Remove some remaining print

---

discrete_optimization/generic_tools/callbacks/stats_retrievers.py
tests/generic_tools/callbacks/test_stats_callbacks.py

-we introduce the BasicStatsCallback and the CpSatStatsCallback as new utilities callback

Adding some callback retrieving time statistics for solver that can produce intermediate results

---

discrete_optimization/generic_tools/callbacks/early_stoppers.py
discrete_optimization/generic_tools/callbacks/sequential_solvers_callback.py
discrete_optimization/generic_tools/callbacks/stats_retrievers.py
discrete_optimization/generic_tools/callbacks/warm_start_callback.py
tests/generic_tools/callbacks/test_earlystopobjective_callback.py
tests/generic_tools/callbacks/test_subresults_callback.py
tests/generic_tools/callbacks/test_warmstart_callback.py
tests/rcpsp/solvers/test_lexico_ortools.py

Few more usefull callback are implemented : 
- warmstart callback between step of sequential solver (like lexico)
- retrieve results of sequential solvers separately (typically to analyse how lexico is running its several phases)
- early stopper based on objective gap (abs or relative)

Callback implementation

---

tests/rcpsp/solvers/test_cp_mzn.py

It takes much too long now on windows.

Skip rcsp multiscenario with mzn test on new github windows runners

---

discrete_optimization/maximum_independent_set/parser.py
tests/maximum_independent_set/myciel3.col
tests/maximum_independent_set/myciel3.mod.col
tests/maximum_independent_set/test_parser.py

The `dimacs_parser()` and `dimacs_parser_nx()` were not following exactly the dimacs specifications (see
http://prolland.free.fr/works/research/dsat/dimacs.html)
In particular
- both were assuming no comment lines
- `dimacs_parser()` was adding node 0 (because trying to number nodes from 0 to n-1) and potentially forgetting node n if not part of an edge
- `dimacs_parser_nx()` was ignoring the number of nodes defined in problem line and only adding nodes enumerated in the edges
We now have `dimacs_parser_nx()` be an alias for `dimacs_parser()` and follow the exact specifications.
Fixes #361.

Fix dimacs parsers

---

discrete_optimization/coloring/solvers/cpsat.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
tests/coloring/solvers/test_solvers.py

- when no sol found (e.g. timeout) => we want to get None instead of 0 (which could mean optimal value found)
- when optimal, we should have bound == obj. We need for that to call `self.solver.BestObjectiveBound()` after solve, which is tighter than the last call to `self.clb.BestObjectiveBound()`

Fix internal objective and bound for cpsat

---

discrete_optimization/generic_tools/lp_tools.py
tests/coloring/solvers/test_solvers.py

- Use `gurobipy.GRB.Callback.MIPSOL_OBJ` to track current best objective value instead of
`gurobipy.GRB.Callback.MIPSOL_OBJBST` which seems not to take into account last sol (and thus provides a "infinite" one when called on the first solution found)
- Update obj and bnd at the end of the solve process (intermediate results can be not tight)

Fix current best objective value and bound for gurobi and mathopt solvers

---

discrete_optimization/coloring/solvers/lp.py
discrete_optimization/generic_tools/lp_tools.py
tests/coloring/solvers/test_solvers.py
tests/knapsack/solvers/test_gurobi_unsat.py

We implement a version of explainability using meta constraints (gathering several constraints).
We rename `explain_unsat()` into `explain_unsat_fine()` to mimic cpmpy wrapper. 
We implement the metaconstraints for the coloring solver as it was done for cpmpy.

Implement `explain_unsat_meta()` for gurobi

---

.github/workflows/build.yml
discrete_optimization/generic_tools/callbacks/stats_retrievers.py
discrete_optimization/generic_tools/dashboard/__init__.py
discrete_optimization/generic_tools/dashboard/config.py
discrete_optimization/generic_tools/dashboard/dashboard.py
discrete_optimization/generic_tools/dashboard/plots.py
discrete_optimization/generic_tools/dashboard/preprocess.py
discrete_optimization/generic_tools/do_solver.py
discrete_optimization/generic_tools/lp_tools.py
discrete_optimization/generic_tools/study/__init__.py
discrete_optimization/generic_tools/study/database.py
discrete_optimization/generic_tools/study/experiment.py
examples/dashboard/retrieve_fake_data.py
examples/dashboard/run_coloring_study.py
examples/dashboard/run_dashboard_coloring_study.py
examples/dashboard/run_dashboard_fake_data.py
pyproject.toml
tests/generic_tools/dashboard/test_dashboard.py

- Database (hdf5 store) to store 
- metrics timeseries (fitness, obj, bound, gap) 
- metadata (pb instance, solver config, solver status)
- experiment class to wrap all that
- Use StatsCallback to populate the database
- Data preprocessing
- normalize index, metadata
- map config to config name  (ensure a bijection, create a name if not
given)
- add metrics (gap absolute and relative)
- aggregate data by config
- extract stats
- Plots
- time evolution of a metric for a config x instance
- time evolution of aggregated metric along instances for a given config
- time evolution of number of instances solved (solver status=="optimal")
- Dashboard
- we use dash library to present the 3 plots with filters on solver configs and instances
- Example: examples/dashboard/run_coloring_study.py + …

Implement a dashboard to sum-up results of a d-o study

---

discrete_optimization/generic_tools/dashboard/config.py
discrete_optimization/generic_tools/dashboard/dashboard.py
discrete_optimization/generic_tools/dashboard/preprocess.py
docs/source/dashboard.md
tests/generic_tools/dashboard/test_dashboard.py

- Add new alias "@withsol": select all instances for which each selected config has found at least one solution
- Limit number of significative digits in tables
- Allow several configs to share the same config name
- raise a warning instead of an error
- show all configs under a name in config explorer tab
- aggregate them in aggregating tabs 
-  Add number of xps and number of xps w/o sol in summary for aggregated metrics
-  Add a tab for aggregated ranks and aggregageted distance to best metric
- Update accordingly the doc

Add functionalities to d-o dashboard

---

discrete_optimization/generic_tools/cpmpy_tools.py
discrete_optimization/generic_tools/lp_tools.py
tests/coloring/solvers/test_solvers.py

- current methods that deduce meta constraints set from minimal fine constraints set are renamed "`***_deduced_meta`" instead of "`***_meta`".
- to find a minimal of meta constraints, we create a cpmpy constraints `all(meta.constraints)` which is the exact translation of what the meta constraint is.

Update explainability methods with meta constraints

---

examples/coloring/run_unsat_interactive_fine.py

Because of the overriding of `solver.get_soft_constraints()`, removing constraints from the model was not sufficient to be taken into account by `solver.get_soft_constraints()`. So we explicitely track the soft constraints passed to `solver.explain_unsat_fine()` to avoid looping infinitely on the same choice of constraints.

Fix interactive example on unsatisfiability with fine constraints

---

discrete_optimization/binpack/solvers/cpsat.py
discrete_optimization/generic_tools/ortools_cpsat_tools.py
tests/coloring/solvers/test_cpsat.py
tests/coloring/solvers/test_solvers.py

When solving twice in a row with an ortools cpsat solver, it starts again from scratch instead of continuing from the best solution it found.
So we add this method (which was already in `CpSatBinPackSolver`) to warm start the solver with the last solution found by itself.
We test it on coloring solver (and split the "test_solvers.py" module for better readibility).

Add `set_warm_start_from_previous_run` method to all cpsat solvers
